### ISSUE TITLE
libcom trilinear_cuda.cpp missing

### ISSUE THREAD

**Issue by Gnoot01** [facebookresearch/sapiens#100]
Hi, in downloading the dependencies from ./install for normal pose, 
- pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
- pip install chumpy scipy munkres tqdm cython fsspec yapf==0.40.1 matplotlib packaging omegaconf ipdb ftfy regex json_tricks terminaltables modelindex prettytable albumentations libcom

I get the following error. Kindly assist, thank you

copying libcom\shadow_generation\source\ldm\modules\midas\midas\blocks.py -> build\lib.win-amd64-cpython-310\libcom\shadow_generation\source\ldm\modules\midas\midas
      copying libcom\shadow_generation\source\ldm\modules\midas\midas\dpt_depth.py -> build\lib.win-amd64-cpython-310\libcom\shadow_generation\source\ldm\modules\midas\midas
      copying libcom\shadow_generation\source\ldm\modules\midas\midas\midas_net.py -> build\lib.win-amd64-cpython-310\libcom\shadow_generation\source\ldm\modules\midas\midas
      copying libcom\shadow_generation\source\ldm\modules\midas\midas\midas_net_custom.py -> build\lib.win-amd64-cpython-310\libcom\shadow_generation\source\ldm\modules\midas\midas
      copying libcom\shadow_generation\source\ldm\modules\midas\midas\transforms.py -> build\lib.win-amd64-cpython-310\libcom\shadow_generation\source\ldm\modules\midas\midas
      copying libcom\shadow_generation\source\ldm\modules\midas\midas\vit.py -> build\lib.win-amd64-cpython-310\libcom\shadow_generation\source\ldm\modules\midas\midas
      copying libcom\shadow_generation\source\ldm\modules\midas\midas\__init__.py -> build\lib.win-amd64-cpython-310\libcom\shadow_generation\source\ldm\modules\midas\midas
      copying libcom\controllable_composition\source\ControlCom\configs\controlcom.yaml -> build\lib.win-amd64-cpython-310\libcom\controllable_composition\source\ControlCom\configs
      copying libcom\fos_score\source\config\config.sfosd.yaml -> build\lib.win-amd64-cpython-310\libcom\fos_score\source\config        
      copying libcom\fos_score\source\config\config_rfosd.yaml -> build\lib.win-amd64-cpython-310\libcom\fos_score\source\config        
      copying libcom\objectstitch\source\ObjectStitch\configs\objectstitch.yaml -> build\lib.win-amd64-cpython-310\libcom\objectstitch\source\ObjectStitch\configs
      copying libcom\painterly_image_harmonization\source\PHDiffusion\stable_diffusion.yaml -> build\lib.win-amd64-cpython-310\libcom\painterly_image_harmonization\source\PHDiffusion
      copying libcom\shadow_generation\source\cldm_v15.yaml -> build\lib.win-amd64-cpython-310\libcom\shadow_generation\source
      running build_ext
      C:\Users\XXX\Desktop\sapiens\sapiens-main\venv\lib\site-packages\torch\utils\cpp_extension.py:380: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'trilinear' extension
      creating build\temp.win-amd64-cpython-310\Release\Users\XXX\AppData\Local\Temp\pip-install-weymt_3l\libcom_4167da7b3ff241dbb6fed25d2477972c\libcom\image_harmonization\source\trilinear_cpp_torch1.11\src
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Users\XXX\Desktop\sapiens\sapiens-main\venv\lib\site-packages\torch\include" "-IC:\Users\XXX\Desktop\sapiens\sapiens-main\venv\lib\site-packages\torch\include\torch\csrc\api\include" "-IC:\Users\XXX\Desktop\sapiens\sapiens-main\venv\lib\site-packages\torch\include\TH" "-IC:\Users\XXX\Desktop\sapiens\sapiens-main\venv\lib\site-packages\torch\include\THC" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\include" "-IC:\Users\XXX\Desktop\sapiens\sapiens-main\venv\include" -IC:\Users\XXX\AppData\Local\Programs\Python\Python310\include -IC:\Users\XXX\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /TpC:\Users\XXX\AppData\Local\Temp\pip-install-weymt_3l\libcom_4167da7b3ff241dbb6fed25d2477972c\libcom/image_harmonization/source/trilinear_cpp_torch1.11/src/trilinear_cuda.cpp /Fobuild\temp.win-amd64-cpython-310\Release\Users\XXX\AppData\Local\Temp\pip-install-weymt_3l\libcom_4167da7b3ff241dbb6fed25d2477972c\libcom/image_harmonization/source/trilinear_cpp_torch1.11/src/trilinear_cuda.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=trilinear -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++17
      trilinear_cuda.cpp
      c1xx: fatal error C1083: Cannot open source file: 'C:\Users\XXX\AppData\Local\Temp\pip-install-weymt_3l\libcom_4167da7b3ff241dbb6fed25d2477972c\libcom/image_harmonization/source/trilinear_cpp_torch1.11/src/trilinear_cuda.cpp': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for libcom
  Running setup.py clean for libcom
Successfully built chumpy antlr4-python3-runtime
Failed to build libcom
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (libcom)

**Comment by Andrez092** [comment]
download

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by Anju023** [comment]
install this
https://bit.ly/4evXrQ6:https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by rawalkhirodkar** [comment]
@Gnoot01 this looks a gpu error when installing libcom.
Please checkout https://github.com/bcmi/libcom for help on installation - you might want to install from source.
