### ISSUE TITLE
Seg Finetune losses dtype error

### ISSUE THREAD

**Issue by matabear-wyx** [facebookresearch/sapiens#102]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/wuyuxiong/yuxiong/sapiens/seg/./tools/train.py", line 125, in <module>
[rank0]:     main()
[rank0]:   File "/home/wuyuxiong/yuxiong/sapiens/seg/./tools/train.py", line 121, in main
[rank0]:     runner.train()
[rank0]:   File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1777, in train
[rank0]:     model = self.train_loop.run()  # type: ignore
[rank0]:   File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
[rank0]:     self.run_epoch()
[rank0]:   File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/mmengine/runner/loops.py", line 113, in run_epoch
[rank0]:     self.run_iter(idx, data_batch)
[rank0]:   File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/mmengine/runner/loops.py", line 129, in run_iter
[rank0]:     outputs = self.runner.model.train_step(
[rank0]:   File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 122, in train_step
[rank0]:     parsed_loss, log_vars = self.module.parse_losses(losses)
[rank0]:   File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 164, in parse_losses
[rank0]:     for loss_name, loss_value in losses.items():
[rank0]: AttributeError: 'tuple' object has no attribute 'items'

**Comment by rawalkhirodkar** [comment]
@matabear-wyx you have a pre-existing mmengine module installed in your environment. Please uninstall this and install from source the engine provided with sapiens.
