### ISSUE TITLE
Lite without detectors

### ISSUE THREAD

**Issue by FriedRonaldo** [facebookresearch/sapiens#104]
Hi, Sapiens team, I am currently trying to use the lite model for feature extraction.

## Setting
model - sapiens_0.6b/sapiens_0.6b_coco_wholebody_best_coco_wholebody_AP_695_torchscript.pt2

torch - '2.2.2+cu121'

## Visualization without a detector

Before that, I visualized pose estimation without detectors.

The output seems incorrect, especially since the points are slightly misaligned.

![image](https://github.com/user-attachments/assets/c9c4e7d9-956d-49fa-bced-6cacd73c2bb6)

## Hanging issue with a detector

In addition, I want to check if the model works well with detectors but it is stuck after loading the model.

How can I resolve these issues?

Thanks.

**Comment by rawalkhirodkar** [comment]
@FriedRonaldo can you share the entire run log and command you used?

Is the det module installation successful? If this is still an issue, you can also swap the bounding box detector with a detector of your choice - say yolox by ultranalytics.

**Comment by rawalkhirodkar** [comment]
@FriedRonaldo Our models are trained for top down pose estimation, using the bbox detector is highly recommended to good results. 

You can either use mmdet (instructions in readme) or modify the code to use other detector of your choice.

**Comment by FriedRonaldo** [comment]
@rawalkhirodkar Thanks for the suggestion! I will close the issue because you confirmed that Sapiens model requires a human detector for the best performance without it, it works worse than expected.
