### ISSUE TITLE
Mask post-processing

### ISSUE THREAD

**Issue by christiankotait** [facebookresearch/sapiens#106]
**Issue and steps taken:**
I've been experiencing issues with the mask output, as they often are patchy and incomplete. I've tried several post-processing techniques, such as using convex hulls and flood filling, but they don't seem to yield satisfactory results consistently.

**Questions:**
- Are there any plans to release mask post-processing utilities?
- Could you point me to any existing resources or recommendations for better mask post-processing techniques? Thanks!

![image](https://github.com/user-attachments/assets/faadd1a1-f7f5-43e0-910f-cd7ef1a6ef8a)

![image](https://github.com/user-attachments/assets/d398c3f8-9c0a-40a5-b343-ed12a5c72790)

**Comment by rawalkhirodkar** [comment]
@christiankotait can you share which backbone are you using? our largest 1b should give the best results. 
- Sorry no plan on this.
- Test-time augmentations will help. Averaging predictions (flipping + multiple crops + sliding window). Refer: [here](https://github.com/open-mmlab/mmsegmentation_

**Comment by christiankotait** [comment]
> @christiankotait can you share which backbone are you using? our largest 1b should give the best results.
> 
> * Sorry no plan on this.
> * Test-time augmentations will help. Averaging predictions (flipping + multiple crops + sliding window). Refer: [here](https://github.com/open-mmlab/mmsegmentation)

I just saw that you removed the 2b backbone, I'll switch back to 1b in that case. Was there a reason for that?
I'll also check test-time augmentations. Thank you!

**Comment by rawalkhirodkar** [comment]
@christiankotait 2b backbone seg finetuning had issues, we are working on resolving this.
Closing this issue for now, feel free to open in future.
