### ISSUE TITLE
Inference time pose estimation

### ISSUE THREAD

**Issue by LitziAdrianaCruz** [facebookresearch/sapiens#110]
I try to do inference with the smallest model (Sapiens-pose-0.3B) on a 45 second video, but the process has already taken more than 2 hours without finishing. Is this an expected behavior? I would appreciate any guidance or recommendations for optimizing inference time on this type of model.

I am using google colab

**Comment by rawalkhirodkar** [comment]
@LitziAdrianaCruz Hey, likely there is an issue with the installation or pytorch version mismatch with the cuda.
- can you test it out on a single image first? This will ensure the setup is correct.
- can you share your environment details and the command you are using for inference? Thanks.

**Comment by Dratlan** [comment]
Hi, it seems there is a the same bug in my machine. while test it for one image, it just stucked as below:
![微信图片_20240925154346](https://github.com/user-attachments/assets/e2a31c6b-4a53-43a8-8997-9afd04a7cd41)
nothing more outputs.
I'm using pose_keypoints133.sh and pose_keypoints308.sh for inference, all got the same problem.
My environment is: torch 2.3.1 + Cuda 12.2 on A100.
while it stucked, I check the GPU usage which is 2071MiB / 81920MiB.
waiting for your reply.

**Comment by Dratlan** [comment]
> Hi, it seems there is a the same bug in my machine. while test it for one image, it just stucked as below: ![微信图片_20240925154346](https://private-user-images.githubusercontent.com/35300160/370615567-e2a31c6b-4a53-43a8-8997-9afd04a7cd41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTIzNjQsIm5iZiI6MTcyNzI1MjA2NCwicGF0aCI6Ii8zNTMwMDE2MC8zNzA2MTU1NjctZTJhMzFjNmItNGE1My00M2E4LTg5OTctOWFmZDA0YTdjZDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4MTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NGVmZWU0Yzg3Mzk2ZTUxNWVhYmUzNDcxNjI0OWJkYTE0MjVjNjI0ZTBlYWRlMzcwOWZjZDhjMjY5MGM1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KP2Nw1HeESMaE9QajSg9iRxXpkofB1CFIj9i_1ErR1A) nothing more outputs. I'm using pose_keypoints133.sh and pose_keypoints308.sh for inference, all got the same problem. My environment is: torch 2.3.1 + Cuda 12.2 on A100. while it stucked, I check the GPU usage which is 2071MiB / 81920MiB. waiting for your reply.

It seems something wrong with the detect module, after remove it, it outputs the result. While, as you said in other issues, with the detector it can get a better result. so can u provide some suggestions for the with_detector_stuck problem?

**Comment by hskwon95** [comment]
I am also facing an issue where the inference time is too long when running  './pose_keypoints17.sh'. I have completed the installation of mmdet, and my environment details are as follows. I haven't made any changes to the shell script apart from adjusting the paths. For reference, I am currently running this in a Docker environment with Ubuntu 20.04.4 LTS. Could you also share how long it usually takes for inference on a single image? And I would also like to use a detector for better results.
If you need any further information, please let me know. Thank you:)

**1. Python Version:** Python 3.10.5
**2. Pip Installed Packages:**
    addict==2.4.0
    contourpy==1.3.0
    cycler==0.12.1
    filelock==3.16.1
    fonttools==4.54.1
    fsspec==2024.9.0
    importlib_metadata==8.5.0
    Jinja2==3.1.4
    json-tricks==3.17.3
    kiwisolver==1.4.7
    markdown-it-py==3.0.0
    MarkupSafe==2.1.5
    matplotlib==3.9.2
    mdurl==0.1.2
    mmengine==0.10.5
    mpmath==1.3.0
    networkx==3.3
    numpy==2.1.1
    nvidia-cublas-cu12==12.1.3.1
    nvidia-cuda-cupti-cu12==12.1.105
    nvidia-cuda-nvrtc-cu12==12.1.105
    nvidia-cuda-runtime-cu12==12.1.105
    nvidia-cudnn-cu12==9.1.0.70
    nvidia-cufft-cu12==11.0.2.54
    nvidia-curand-cu12==10.3.2.106
    nvidia-cusolver-cu12==11.4.5.107
    nvidia-cusparse-cu12==12.1.0.106
    nvidia-nccl-cu12==2.20.5
    nvidia-nvjitlink-cu12==12.6.68
    nvidia-nvtx-cu12==12.1.105
    opencv-python==4.10.0.84
    packaging==24.1
    pillow==10.4.0
    platformdirs==4.3.6
    pycocotools==2.0.8
    Pygments==2.18.0
    pyparsing==3.1.4
    python-dateutil==2.9.0.post0
    PyYAML==6.0.2
    rich==13.8.1
    scipy==1.14.1
    shapely==2.0.6
    six==1.16.0
    sympy==1.13.3
    termcolor==2.4.0
    terminaltables==3.1.10
    tomli==2.0.1
    torch==2.4.1
    torchaudio==2.4.1
    torchvision==0.19.1
    tqdm==4.66.5
    triton==3.0.0
    typing_extensions==4.12.2
    yapf==0.40.2
    zipp==3.20.2
**3. Editable Installations:**
sapiens-cv==1.0.0 (Path: /home/ps0/code/sapiens/cv)
sapiens-det==1.0.0 (Path: /home/ps0/code/sapiens/det)
sapiens-engine==1.0.0 (Path: /home/ps0/code/sapiens/engine)
**4. CUDA Version (nvcc):**
nvcc: NVIDIA (R) Cuda compiler driver
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
**5. PyTorch CUDA Version Check(python -c "import torch; print(torch.version.cuda)") :** 12.1
**6. GPU Information:**
Driver Version: 535.183.01
CUDA Version: 12.2
GPUs: two NVIDIA GeForce RTX 4090 GPUs.

**Comment by rawalkhirodkar** [comment]
@Dratlan consider entirely eliminating the mmdet detector in the pose-lite inference. You can do this as follows:

- remove the mmdet imports and variables from this file, eg. [here](https://github.com/facebookresearch/sapiens/blob/cee84394a34c2bc5e7cde6552e85fe3111092a33/lite/demo/vis_pose.py#L36)
- use the [YOLO-v8 detector](https://github.com/ultralytics/ultralytics), this code is just a rough illustration.
```
from ultralytics import YOLO
detector = YOLO("yolov8n.pt")
results = model("path/to/image.jpg") ## modify to only get the person bbox
```
- swap with the YOLO bboxes here: [link](https://github.com/facebookresearch/sapiens/blob/cee84394a34c2bc5e7cde6552e85fe3111092a33/lite/demo/detector_utils.py#L158)
- bboxes are N x 5: x1, x2, y1, y2, score. N = number of detections in the image.

Sorry for the crude code, but the core issue here is the installation of mmdet.

**Comment by rawalkhirodkar** [comment]
@hskwon95 You might be facing the same issue. 

- can you perform inference successfully on a single image?
- is it still stalling if you remove the detection configurations?

if yes, please consider replacing the bbox detector as above.

**Comment by fnuabhimanyu8713** [comment]
@rawalkhirodkar I have replaced the mmdet detector with the YOLOv8 detector, but still facing the issue with inference. After probing further this is where its getting stuck:
```
pose_preprocess_pool.run(args_list)
````
Is there something more I can test to locate the issue?

**Comment by rawalkhirodkar** [comment]
@fnuabhimanyu8713 thank you for investigating the issue.

- The stall at pose_preprocess_pool suggests the environment you are using is not compatible with the parallelization we are using. For instance, the number of threads is being set to 0 [here](https://github.com/facebookresearch/sapiens/blob/cee84394a34c2bc5e7cde6552e85fe3111092a33/lite/demo/vis_pose.py#L340) (if cpu count is 1).
- Removing multi-processing code will help
- simply replace all parallelizing functions calls with sequential processing.

**Comment by fnuabhimanyu8713** [comment]
Thank @rawalkhirodkar for prompt reply. My CPU has 32 cores, so it shouldn't be an issue. 
What other parameter can be an issue?
Also any tip on where to start removing multi-processing code.

**Comment by rawalkhirodkar** [comment]
@fnuabhimanyu8713 thank you for the response. 
Here is a rough code to remove parallelization from the pose-lite-demo :

```
# Remove these imports as they're no longer needed
# import multiprocessing as mp
# from multiprocessing import cpu_count, Pool, Process
# from worker_pool import WorkerPool

# Remove or comment out these lines
# mp.log_to_stderr()
# pose_preprocess_pool = WorkerPool(
#     preprocess_pose, processes=max(min(args.batch_size, cpu_count()), 1)
# )
# img_save_pool = WorkerPool(
#     img_save_and_viz, processes=max(min(args.batch_size, cpu_count()), 1)
# )

# Replace the multiprocessing data loader with a sequential one
inference_dataloader = torch.utils.data.DataLoader(
    inference_dataset,
    batch_size=args.batch_size,
    shuffle=False,
    num_workers=0,  # Set to 0 for sequential processing
)

# Replace the parallel pose preprocessing with sequential processing
# args_list = [
#     (
#         i,
#         bbox_list,
#         (input_shape[1], input_shape[2]),
#         [123.5, 116.5, 103.5],
#         [58.5, 57.0, 57.5],
#     )
#     for i, bbox_list in zip(batch_orig_imgs.numpy(), bboxes_batch)
# ]
# pose_ops = pose_preprocess_pool.run(args_list)

pose_ops = []
for i, bbox_list in zip(batch_orig_imgs.numpy(), bboxes_batch):
    pose_op = preprocess_pose(
        i,
        bbox_list,
        (input_shape[1], input_shape[2]),
        [123.5, 116.5, 103.5],
        [58.5, 57.0, 57.5],
    )
    pose_ops.append(pose_op)

# Replace the parallel image saving with sequential processing
# args_list = [
#     (
#         i.numpy(),
#         r,
#         os.path.join(args.output_root, os.path.basename(img_name)),
#         (input_shape[2], input_shape[1]),
#         scale,
#         KPTS_COLORS,
#         args.kpt_thr,
#         args.radius,
#     )
#     for i, r, img_name in zip(
#         batch_orig_imgs[:valid_images_len],
#         batched_results[:valid_images_len],
#         batch_image_name,
#     )
# ]
# img_save_pool.run_async(args_list)

for i, r, img_name in zip(
    batch_orig_imgs[:valid_images_len],
    batched_results[:valid_images_len],
    batch_image_name,
):
    img_save_and_viz(
        i.numpy(),
        r,
        os.path.join(args.output_root, os.path.basename(img_name)),
        (input_shape[2], input_shape[1]),
        scale,
        KPTS_COLORS,
        args.kpt_thr,
        args.radius,
    )

# Remove these lines as they're no longer needed
# pose_preprocess_pool.finish()
# img_save_pool.finish()
```

Alternatively, you can take a look at the [pose-demo repo](https://huggingface.co/spaces/facebook/sapiens-pose) for an example of sequential processing.

**Comment by fnuabhimanyu8713** [comment]
Serialization helped! Now I am able to run the pose detection

**Comment by Dratlan** [comment]
@fnuabhimanyu8713 Can u share your replaced code with a fork or otherelse? Thank you

**Comment by hskwon95** [comment]
By following the steps above, I was able to modify the code and run pose detection. I hope my code can help many people

vis_pose.py
`# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

import itertools
#import multiprocessing as mp
import os
import time
import warnings
from argparse import ArgumentParser
from collections import defaultdict
from functools import partial
#from multiprocessing import cpu_count, Pool, Process
from typing import List, Optional, Sequence, Union

import cv2
import json_tricks as json
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from adhoc_image_dataset import AdhocImageDataset
from classes_and_palettes import (
    COCO_KPTS_COLORS,
    COCO_WHOLEBODY_KPTS_COLORS,
    GOLIATH_KPTS_COLORS,
)
from pose_utils import nms, top_down_affine_transform, udp_decode

from tqdm import tqdm

#from worker_pool import WorkerPool

'''
try:
    from mmdet.apis import inference_detector, init_detector
    from mmdet.structures import DetDataSample, SampleList
    from mmdet.utils import get_test_pipeline_cfg

    has_mmdet = True
except (ImportError, ModuleNotFoundError):
    has_mmdet = False
'''
from ultralytics import YOLO

warnings.filterwarnings("ignore", category=UserWarning, module="torchvision")
warnings.filterwarnings("ignore", category=UserWarning, module="mmengine")
warnings.filterwarnings("ignore", category=UserWarning, module="torch.functional")
warnings.filterwarnings("ignore", category=UserWarning, module="json_tricks.encoders")

timings = {}
BATCH_SIZE = 48


def preprocess_pose(orig_img, bboxes_list, input_shape, mean, std):
    """Preprocess pose images and bboxes."""
    preprocessed_images = []
    centers = []
    scales = []
    for bbox in bboxes_list:
        img, center, scale = top_down_affine_transform(orig_img.copy(), bbox)
        img = cv2.resize(
            img, (input_shape[1], input_shape[0]), interpolation=cv2.INTER_LINEAR
        ).transpose(2, 0, 1)
        img = torch.from_numpy(img)
        img = img[[2, 1, 0], ...].float()
        mean = torch.Tensor(mean).view(-1, 1, 1)
        std = torch.Tensor(std).view(-1, 1, 1)
        img = (img - mean) / std
        preprocessed_images.append(img)
        centers.extend(center)
        scales.extend(scale)
    return preprocessed_images, centers, scales


def batch_inference_topdown(
    model: nn.Module,
    imgs: List[Union[np.ndarray, str]],
    dtype=torch.bfloat16,
    flip=False,
):
    with torch.no_grad(), torch.autocast(device_type="cuda", dtype=dtype):
        heatmaps = model(imgs.cuda())
        if flip:
            heatmaps_ = model(imgs.to(dtype).cuda().flip(-1))
            heatmaps = (heatmaps + heatmaps_) * 0.5
        imgs.cpu()
    return heatmaps.cpu()


def img_save_and_viz(
    img, results, output_path, input_shape, heatmap_scale, kpt_colors, kpt_thr, radius
):
    # pred_instances_list = split_instances(result)
    heatmap = results["heatmaps"]
    centres = results["centres"]
    scales = results["scales"]
    img_shape = img.shape
    instance_keypoints = []
    instance_scores = []
    # print(scales[0], centres[0])
    for i in range(len(heatmap)):
        result = udp_decode(
            heatmap[i].cpu().unsqueeze(0).float().data[0].numpy(),
            input_shape,
            (int(input_shape[0] / heatmap_scale), int(input_shape[1] / heatmap_scale)),
        )

        keypoints, keypoint_scores = result
        keypoints = (keypoints / input_shape) * scales[i] + centres[i] - 0.5 * scales[i]
        instance_keypoints.append(keypoints[0])
        instance_scores.append(keypoint_scores[0])

    pred_save_path = output_path.replace(".jpg", ".json").replace(".png", ".json")

    with open(pred_save_path, "w") as f:
        json.dump(
            dict(
                instance_info=[
                    {
                        "keypoints": keypoints.tolist(),
                        "keypoint_scores": keypoint_scores.tolist(),
                    }
                    for keypoints, keypoint_scores in zip(
                        instance_keypoints, instance_scores
                    )
                ]
            ),
            f,
            indent="\t",
        )
    # img = pyvips.Image.new_from_array(img)
    instance_keypoints = np.array(instance_keypoints).astype(np.float32)
    instance_scores = np.array(instance_scores).astype(np.float32)

    keypoints_visible = np.ones(instance_keypoints.shape[:-1])
    for kpts, score, visible in zip(
        instance_keypoints, instance_scores, keypoints_visible
    ):
        kpts = np.array(kpts, copy=False)

        if (
            kpt_colors is None
            or isinstance(kpt_colors, str)
            or len(kpt_colors) != len(kpts)
        ):
            raise ValueError(
                f"the length of kpt_color "
                f"({len(kpt_colors)}) does not matches "
                f"that of keypoints ({len(kpts)})"
            )

        # draw each point on image
        for kid, kpt in enumerate(kpts):
            if score[kid] < kpt_thr or not visible[kid] or kpt_colors[kid] is None:
                # skip the point that should not be drawn
                continue

            color = kpt_colors[kid]
            if not isinstance(color, str):
                color = tuple(int(c) for c in color[::-1])
            img = cv2.circle(img, (int(kpt[0]), int(kpt[1])), int(radius), color, -1)
    cv2.imwrite(output_path, img)


def fake_pad_images_to_batchsize(imgs):
    return F.pad(imgs, (0, 0, 0, 0, 0, 0, 0, BATCH_SIZE - imgs.shape[0]), value=0)

def load_model(checkpoint, use_torchscript=False):
    if use_torchscript:
        return torch.jit.load(checkpoint)
    else:
        return torch.export.load(checkpoint).module()

def main():
    """Visualize the demo images.
    Using mmdet to detect the human.
    """
    parser = ArgumentParser()
    parser.add_argument("pose_checkpoint", help="Checkpoint file for pose")
    parser.add_argument("--det-config", default="", help="Config file for detection")
    parser.add_argument("--det-checkpoint", default="", help="Checkpoint file for detection")
    parser.add_argument("--input", type=str, default="", help="Image/Video file")
    parser.add_argument(
        "--num_keypoints",
        type=int,
        default=133,
        help="Number of keypoints in the pose model. Used for visualization",
    )
    parser.add_argument(
        "--shape",
        type=int,
        nargs="+",
        default=[1024, 768],
        help="input image size (height, width)",
    )
    parser.add_argument(
        "--output-root",
        type=str,
        default="",
        help="root of the output img file. "
        "Default not saving the visualization images.",
    )
    parser.add_argument(
        "--batch_size",
        "--batch-size",
        type=int,
        default=48,
        help="Set batch size to do batch inference. ",
    )
    parser.add_argument(
        "--fp16", action="store_true", default=False, help="Model inference dtype"
    )
    parser.add_argument("--device", default="cuda:0", help="Device used for inference")
    parser.add_argument(
        "--det-cat-id",
        type=int,
        default=0,
        help="Category id for bounding box detection model",
    )
    parser.add_argument(
        "--bbox-thr", type=float, default=0.3, help="Bounding box score threshold"
    )
    parser.add_argument(
        "--nms-thr", type=float, default=0.3, help="IoU threshold for bounding box NMS"
    )
    parser.add_argument(
        "--kpt-thr", type=float, default=0.3, help="Visualizing keypoint thresholds"
    )
    parser.add_argument(
        "--radius", type=int, default=9, help="Keypoint radius for visualization"
    )
    parser.add_argument(
        "--heatmap-scale", type=int, default=4, help="Heatmap scale for keypoints. Image to heatmap ratio"
    )
    parser.add_argument(
        "--flip",
        type=bool,
        default=False,
        help="Flip the input image horizontally and inference again",
    )

    args = parser.parse_args()

    if args.det_config is None or args.det_config == "":
        use_det = False
    else:
        use_det = True
        #assert has_mmdet, "Please install mmdet to run the demo."
        assert args.det_checkpoint is not None
        
        from detector_utils import (
            #adapt_mmdet_pipeline,
            #init_detector,
            process_images_detector,
        )

    assert args.input != ""
    # assert args.det_config is not None

    if len(args.shape) == 1:
        input_shape = (3, args.shape[0], args.shape[0])
    elif len(args.shape) == 2:
        input_shape = (3,) + tuple(args.shape)
    else:
        raise ValueError("invalid input shape")

    #mp.log_to_stderr()
    torch._inductor.config.force_fuse_int_mm_with_mul = True
    torch._inductor.config.use_mixed_mm = True

    start = time.time()

    if not os.path.exists(args.output_root):
        os.makedirs(args.output_root)

    assert args.output_root != ""
    args.pred_save_path = (
        f"{args.output_root}/results_"
        f"{os.path.splitext(os.path.basename(args.input))[0]}.json"
    )

    # build detector
    if use_det:
        detector =YOLO(args.det_checkpoint)
        '''
        detector = init_detector(
            args.det_config, args.det_checkpoint, device=args.device
        )
        detector.cfg = adapt_mmdet_pipeline(detector.cfg)
        '''

    # build pose estimator
    USE_TORCHSCRIPT = '_torchscript' in args.pose_checkpoint

    # build the model from a checkpoint file
    pose_estimator = load_model(args.pose_checkpoint, USE_TORCHSCRIPT)

    ## no precision conversion needed for torchscript. run at fp32
    if not USE_TORCHSCRIPT:
        dtype = torch.half if args.fp16 else torch.bfloat16
        pose_estimator.to(dtype)
        pose_estimator = torch.compile(pose_estimator, mode="max-autotune", fullgraph=True)
    else:
        dtype = torch.float32  # TorchScript models use float32
        pose_estimator = pose_estimator.to(args.device)

    global BATCH_SIZE
    BATCH_SIZE = args.batch_size

    input = args.input
    image_names = []

    # Check if the input is a directory or a text file
    if os.path.isdir(input):
        input_dir = input  # Set input_dir to the directory specified in input
        '''
        image_names = [
            image_name
            for image_name in sorted(os.listdir(input_dir))
            if image_name.endswith(".jpg") or image_name.endswith(".png")
        ]
        '''
    elif os.path.isfile(input) and input.endswith(".txt"):
        # If the input is a text file, read the paths from it and set input_dir to the directory of the first image
        with open(input, "r") as file:
            image_paths = [line.strip() for line in file if line.strip()]
        '''
        image_names = [
            os.path.basename(path) for path in image_paths
        ]  # Extract base names for image processing
        input_dir = (
            os.path.dirname(image_paths[0]) if image_paths else ""
        )  # Use the directory of the first image path
        '''
    scale = args.heatmap_scale
    inference_dataset = AdhocImageDataset(
        #[os.path.join(input_dir, img_name) for img_name in image_names],
        image_paths,
    )  # do not provide preprocess args for detector as we use mmdet
    inference_dataloader = torch.utils.data.DataLoader(
        inference_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=0,  # Set to 0 for sequential processing
    )
    #pose_preprocess_pool = WorkerPool(
    #    preprocess_pose, processes=max(min(args.batch_size, cpu_count()) // 4, 4)
    #)
    #img_save_pool = WorkerPool(
    #    img_save_and_viz, processes=max(min(args.batch_size, cpu_count()) // 4, 4)
    #)

    KPTS_COLORS = COCO_WHOLEBODY_KPTS_COLORS  ## 133 keypoints

    if args.num_keypoints == 17:
        KPTS_COLORS = COCO_KPTS_COLORS
    elif args.num_keypoints == 308:
        KPTS_COLORS = GOLIATH_KPTS_COLORS

    for batch_idx, (batch_image_name, batch_orig_imgs, batch_imgs) in tqdm(
        enumerate(inference_dataloader), total=len(inference_dataloader)
    ):
        orig_img_shape = batch_orig_imgs.shape
        valid_images_len = len(batch_orig_imgs)
        if use_det:
            #imgs = batch_orig_imgs.clone()[
            #    ..., [2, 1, 0]
            #]  # since detector uses mmlab, directly use original images
            #bboxes_batch = process_images_detector(args, imgs.numpy(), detector)
            bboxes_batch = process_images_detector(args, batch_image_name, detector)
        else:
            bboxes_batch = [[] for _ in range(len(batch_orig_imgs))]

        assert len(bboxes_batch) == valid_images_len

        for i, bboxes in enumerate(bboxes_batch):
            if len(bboxes) == 0:
                bboxes_batch[i] = np.array(
                    [[0, 0, orig_img_shape[1], orig_img_shape[0]]]
                )

        img_bbox_map = {}
        for i, bboxes in enumerate(bboxes_batch):
            img_bbox_map[i] = len(bboxes)

        # args_list = [
        #     (
        #         i,
        #         bbox_list,
        #         (input_shape[1], input_shape[2]),
        #         [123.5, 116.5, 103.5],
        #         [58.5, 57.0, 57.5],
        #     )
        #     for i, bbox_list in zip(batch_orig_imgs.numpy(), bboxes_batch)
        # ]
 
        # pose_ops = pose_preprocess_pool.run(args_list)
    
        pose_ops = []
        for i, bbox_list in zip(batch_orig_imgs.numpy(), bboxes_batch):
            pose_op = preprocess_pose(
                i,
                bbox_list,
                (input_shape[1], input_shape[2]),
                [123.5, 116.5, 103.5],
                [58.5, 57.0, 57.5],
            )
            pose_ops.append(pose_op)
 
        pose_imgs, pose_img_centers, pose_img_scales = [], [], []
        for op in pose_ops:
            pose_imgs.extend(op[0])
            pose_img_centers.extend(op[1])
            pose_img_scales.extend(op[2])

        n_pose_batches = (len(pose_imgs) + args.batch_size - 1) // args.batch_size

        # use this to tell torch compiler the start of model invocation as in 'flip' mode the tensor output is overwritten
        torch.compiler.cudagraph_mark_step_begin()  
        pose_results = []
        for i in range(n_pose_batches):
            imgs = torch.stack(
                pose_imgs[i * args.batch_size : (i + 1) * args.batch_size], dim=0
            )
            valid_len = len(imgs)
            imgs = fake_pad_images_to_batchsize(imgs)
            pose_results.extend(
                batch_inference_topdown(pose_estimator, imgs, dtype=dtype)[:valid_len]
            )

        batched_results = []
        for _, bbox_len in img_bbox_map.items():
            result = {
                "heatmaps": pose_results[:bbox_len].copy(),
                "centres": pose_img_centers[:bbox_len].copy(),
                "scales": pose_img_scales[:bbox_len].copy(),
            }
            batched_results.append(result)
            del (
                pose_results[:bbox_len],
                pose_img_centers[:bbox_len],
                pose_img_scales[:bbox_len],
            )

        assert len(batched_results) == len(batch_orig_imgs)

        # args_list = [
        #     (
        #         i.numpy(),
        #         r,
        #         os.path.join(args.output_root, os.path.basename(img_name)),
        #         (input_shape[2], input_shape[1]),
        #         scale,
        #         KPTS_COLORS,
        #         args.kpt_thr,
        #         args.radius,
        #     )
        #     for i, r, img_name in zip(
        #         batch_orig_imgs[:valid_images_len],
        #         batched_results[:valid_images_len],
        #         batch_image_name,
        #     )
        # ]
        # img_save_pool.run_async(args_list)

        for i, r, img_name in zip(
            batch_orig_imgs[:valid_images_len],
            batched_results[:valid_images_len],
            batch_image_name,
        ):
            img_save_and_viz(
                i.numpy(),
                r,
                os.path.join(args.output_root, os.path.basename(img_name)),
                (input_shape[2], input_shape[1]),
                scale,
                KPTS_COLORS,
                args.kpt_thr,
                args.radius,
            )

    #pose_preprocess_pool.finish()
    #img_save_pool.finish()

    total_time = time.time() - start
    print(
        f"\033[92mTotal inference time: {total_time:.2f} seconds. "
    )


if __name__ == "__main__":
    main()`

**Comment by fnuabhimanyu8713** [comment]
@Dratlan 
Forked repo with changes: https://github.com/fnuabhimanyu8713/sapiens

**Comment by Dratlan** [comment]
@fnuabhimanyu8713 Thank you

**Comment by Gnoot01** [comment]
> @Dratlan Forked repo with changes: https://github.com/fnuabhimanyu8713/sapiens Also I am using low-res images (110x126) that's why I needed the yolo detection. But in case you are using high-res images, you can disable that. Helps with faster inference

With low res images, when you resize it back to view on screen, it becomes blurry, how do you work around that?
