### ISSUE TITLE
Trying to download sapiens_lite model for pose estimation

### ISSUE THREAD

**Issue by fnuabhimanyu8713** [facebookresearch/sapiens#111]
I am downloading weights from Hugging Face for sapiens_lite. 
Current error: Error 404sapiens_lite_host does not exist on "main"

**Comment by fnuabhimanyu8713** [comment]
Update: 
Link on this [page](https://github.com/facebookresearch/sapiens/blob/main/lite/README.md) :  is not working. Although the main link is working. Can download lite weights from there. 

Also whats the time taken to run ./pose_keypoints308.sh in MODE=torchscript.

**Comment by rawalkhirodkar** [comment]
@fnuabhimanyu8713 inference time depends on your backboke. Eg: sapiens-0.3b is about 17 fps.
