### ISSUE TITLE
Working on Edge Devices!

### ISSUE THREAD

**Issue by johnnynunez** [facebookresearch/sapiens#112]
A silly demo..
![3e7845eb-7e1c-4979-8de3-2fc7769ff058](https://github.com/user-attachments/assets/9defbf91-799f-4908-8a6a-f87b258fd24f)

**Comment by rawalkhirodkar** [comment]
@johnnynunez this is very cool!
Do you mind contributing this to the repo as  a PR?

**Comment by johnnynunez** [comment]
> @johnnynunez this is very cool! Do you mind contributing this to the repo as a PR?

Anyone can use it with jetson-containers. Can be optimized a lot. TensorRT, move data transfers etc

but the repository can be installed now easily https://github.com/dusty-nv/jetson-containers/pull/641#event-14391497558
