### ISSUE TITLE
Unable to set batch size > 48 for Lite Pose Estimation?

### ISSUE THREAD

**Issue by dnandakumar-nv** [facebookresearch/sapiens#115]
Setting the batch size to 64 in the `pose_keypoints308.sh` script of Sapiens Lite with the `sapiens_1b/sapiens_1b_goliath_best_goliath_AP_640_bfloat16.pt2` model produces the following error:

`sapiens_lite/lib/python3.10/site-packages/torch/_export/utils.py", line 123, in _check_input_constraints_for_graph
    raise RuntimeError(
RuntimeError: Expected input at *args[0].shape[0] to be <= 48, but got 64`

Looks like the maximum supported batch size if 48? Is there a way to increase this batch size? Running on an `80GB H100 GPU` with packages

`pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=12.1` 

installed in Conda

**Comment by rawalkhirodkar** [comment]
@dnandakumar-nv thank you for spotting this.
The bfloat16 models were compiled with batch size 48, we did not expect it to be the maximum upperbound on batch size during inference. 

If you wish to exceed 48, you would have to port the original models to bfloat16 yourself using a higher batchsize. Check out the pose/scripts/optimize scripts.
