### ISSUE TITLE
Input image size for pose estimation

### ISSUE THREAD

**Issue by Zeyu-Zhu** [facebookresearch/sapiens#117]
Does lite pose estimation demo support image input of any size?

First, I want to share that I ran the demo on the given sample(reef1 image size: 3840x2160) successfully using the script 'pose_keypoints133.sh'. 

However, when I ran the demo with my own image(size: 544x960), I faced the error "RuntimeError: The size of tensor a (2040) must match the size of tensor b (3072) at non-singleton dimension 1".

And I did notice that in dataset there is _preprocess funcation to resize the image, but in the inference process(vis_pose.py, line 358) 'batch_orig_imgs' is used instead of 'batch_imgs' which means the input image is not resized.

Can you tell me if ite pose estimation demo support image input of any size or what I should do to support it?

**Comment by rawalkhirodkar** [comment]
@Zeyu-Zhu line 62 resizes the bbox image patch to model input size (1024 × 768).

The demo should work on any image size.
Can you share an example image to reproduce the error?

**Comment by Zeyu-Zhu** [comment]
Thanks for the help! 

I checked the code and it turned out that the '--shape' param should be (1024 × 768) as you said. At first, I thought it meant the input image size instead of the model input size. So I shouldn't change that for inferencing images with different sizes.

Problem solved, thanks again!
