### ISSUE TITLE
How to extract cls_token from encoder output when using torchscript model? 

### ISSUE THREAD

**Issue by Franckevicius** [facebookresearch/sapiens#118]
With full model I can do 

```py
inferencer = FeatureExtractor(model=args.config, pretrained=args.checkpoint, device=args.device)
inferencer.model.backbone.out_type = "cls_token"  # extract embedding
```

what's the equivalent if I want to extract `cls_token` from torchscript model (`sapiens_1b_epoch_173_torchscript.pt2`)? `model.backbone.cls_token` doesn't change after processing some input.

**Comment by rawalkhirodkar** [comment]
@Franckevicius in this case, we would recommend using the full model. The lite inference only supports extracting spatial feature maps.
