### ISSUE TITLE
Typo on section 3.1, Figure 3 description 

### ISSUE THREAD

**Issue by raphaelamorim** [facebookresearch/sapiens#12]
Figure 3. Sapiens **resonstruction** on unseen images.

**Comment by raphaelamorim** [comment]
<img width="490" alt="image" src="https://github.com/user-attachments/assets/e63b9b7d-3237-46b1-9a8a-b63b445517b5">

**Comment by rawalkhirodkar** [comment]
Thank you for pointing this. Fixed.
