### ISSUE TITLE
Lite version model inference stuck for 1hr

### ISSUE THREAD

**Issue by kyuBin422** [facebookresearch/sapiens#121]
I use the 4070 to load the model and let it run the inference by" pose_keypoints17.sh". However it stuck for 1 hr without any update
``
(sapiens_lite) yanjiuyuan@debian:~/Desktop/YB/sapiens/lite/scripts/demo/torchscript$ bash pose_keypoints17.sh 
Distributing 100 image paths into 1 jobs.
/home/yanjiuyuan/Desktop/YB/sapiens/engine/mmengine/optim/optimizer/zero_optimizer.py:16: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Loads checkpoint by local backend from path: /home/yanjiuyuan/sapiens_lite_host/torchscript/detector/checkpoints/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth on server: debian
/home/yanjiuyuan/Desktop/YB/sapiens/engine/mmengine/runner/checkpoint.py:354: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, map_location=map_location)
Done: Loaded checkpoint from /home/yanjiuyuan/sapiens_lite_host/torchscript/detector/checkpoints/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth on server: debian
  0%|                                                                                                | 0/13 [00:00<?, ?it/s]/home/yanjiuyuan/Desktop/YB/sapiens/det/mmdet/models/layers/se_layer.py:163: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False):
/home/yanjiuyuan/Desktop/YB/sapiens/det/mmdet/models/backbones/csp_darknet.py:123: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False):
``

**Comment by rawalkhirodkar** [comment]
@kyuBin422 please checkout https://github.com/facebookresearch/sapiens/issues/110. Likely an issue with parallelism on your hardware, serialization will fix it.
