### ISSUE TITLE
Absence of detector checkpoint

### ISSUE THREAD

**Issue by emilharutyunyaNN** [facebookresearch/sapiens#123]
I tried finding the detector checkpoint, and to my surprise it was not mentioned in the manuals but present in the shell code. I tried downloading from hugging face, but the code has a "_pickle.UnpicklingError: invalid load key, 'v'." meaning the checkpoint can't be loaded. I was wondering if there is a pickleable checkpoint available, and how to resolve this error

**Comment by rawalkhirodkar** [comment]
@emilharutyunyaNN are you referring to this?
https://huggingface.co/facebook/sapiens-pose-bbox-detector/blob/main/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth

This is mentioned in the huggingface collection. 
If the pickle issue persists, simply download the model weight separately using wget or using a browser.
