### ISSUE TITLE
Detector checkpoint can't be loaded by pickle

### ISSUE THREAD

**Issue by emilharutyunyaNN** [facebookresearch/sapiens#124]
after creating the directory and downloading the checkpoint for the bbox detector I get this error when I run the inference shell file 
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by rawalkhirodkar** [comment]
@emilharutyunyaNN can you share the entire command you used to run along with the error log? Thanks.

**Comment by emilharutyunyaNN** [comment]
the issue was with lfs not being downloaded properly, I had to use git lfs pull which didn't work as well. So I ended up downloading in the local environment and copying it to the server with scp. Problem solved thank you
