### ISSUE TITLE
Streamlining pose estimation demo execution

### ISSUE THREAD

**Issue by AmitMY** [facebookresearch/sapiens#125]
I wanted to get pose estimation to run, and because of some version mismatches struggled a bit.
I think the process should be streamlined a little more, specifically, the installation, some requirement files specify `mmcv<2.1.0` but others `<2.2.0` which affects mmdet as well.

Here is the installation order I find to work:

```bash
# Clone the repository
git clone https://github.com/facebookresearch/sapiens.git
cd sapiens

# Install the environment
./_install/conda.sh
conda activate sapiens
pip install -e ./pose
pip install -r pose/requirements/runtime.txt
pip install -r pose/requirements/mminstall.txt
pip install -U mmdet "mmcv>=2.0.0rc4, <2.2.0"
pip install tqdm
pip install -e ./pretrain
```

Then, for reference, I am downloading the checkpoints like so:
```bash
# Download the models from huggingface
pip install -U "huggingface_hub[cli]"
SAPIENS_ROOT="$(pwd)"
mkdir -p "$SAPIENS_ROOT/checkpoints/sapiens_host/detector/checkpoints/rtmpose"

# Must download the pose detector
huggingface-cli download facebook/sapiens-pose-bbox-detector \
  rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth \
  --local-dir "$SAPIENS_ROOT/checkpoints/sapiens_host/detector/checkpoints/rtmpose"

# This downloads one specific pose model (not all sizes)
# If you want all sizes, remove the file name.
huggingface-cli download noahcao/sapiens-pose-coco \
  sapiens_host/pose/checkpoints/sapiens_0.3b/sapiens_0.3b_coco_best_coco_AP_796.pth \
  --local-dir "$SAPIENS_ROOT/checkpoints"
```

And to run the model, I had to perform multiple manual changes (see TODO).
It would be nicer, in my opinion, if the scripts would:
1. check if GPUs are available, otherwise use CPU automatically
2. fix the error in `demo_vis.py`
3. allow setting model size as a variable, so no manual changes to the bash scripts are necessary (makes it easier to keep to the latest version of your repository)

```bash
# Run the model
cd pose/scripts/demo/local/
chmod +x *
export SAPIENS_CHECKPOINT_ROOT="$SAPIENS_ROOT/checkpoints/sapiens_host"
export OUTPUT="$SAPIENS_ROOT/output"
export INPUT="$SAPIENS_ROOT/pose/demo/data/itw_videos/reel1"

# TODO: Manual changes
#       In line 82 of keypoints17.sh, add "--device="cpu" \" if no GPU is available
#       In demo_vis.py, line 192, comment override_ckpt_meta=True
#       In keypoints17.sh uncomment the 0.3b model and comment the others
./keypoints17.sh
```

Thanks for this lovely repository!

**Comment by rawalkhirodkar** [comment]
@AmitMY thank you for the suggestions. I will incorporate these to the repo.

On the installation, if conda.sh was successful, you should not need any other additional installs.

The .sh script installs everything from source, which are all version compatible. Any addons after this should not be required. 

I will add the option for cpu support, thanks. Btw changing the model input size is not supported and will not give the reported results.

**Comment by AmitMY** [comment]
I understand, but in my case, additional installs were needed. You can check for yourself these commands in a docker or something :) I think possibly the install script should early-exit if something fails. (`set -e`)

Thanks for adding CPU support.

I think that supporting the model size would be a nice add, so one does not have to modify the shell script, and can just run it as is.

**Comment by rawalkhirodkar** [comment]
@AmitMY, we have indeed verified the installation from scratch in multiple environments. Let me cross-check again. It would be helpful if you could share your installation log as well for a quick peek.

The model input size is not supposed to be changed, these are vision transformers which work on a fixed size input. It is hard coded everywhere, and users are not instructed to change it.

**Comment by AmitMY** [comment]
Oh sorry! misunderstanding. When I say "Model size" I mean parameter count. You have 4 sizes available, and to change between them the user is requested to modify this file, these lines:
https://github.com/facebookresearch/sapiens/blob/2c9034f7fffc10e99b2d850631c21a63d041cb3f/pose/scripts/demo/local/keypoints17.sh#L10-L14
