### ISSUE TITLE
Pose estimation finetuning: mmpretrain Arch sapiens_0.3b is not in default archs

### ISSUE THREAD

**Issue by ysuter** [facebookresearch/sapiens#127]
Hi,
I am trying to finetune the pose models for infrared image data. I prepared a dataset with images padded to the size [768, 1024] to be able to use the finetuning scripts you provide. I structured the data as mentioned [here](https://github.com/facebookresearch/sapiens/blob/main/docs/finetune/POSE_README.md#-1-data-preparation) like the coco dataset with 17 keypoints. As I would like to tune the 17 keypoint model, I left the $DATASET parameter as 'coco'.

I am getting the following error:
`File "/home/myname/miniconda3/envs/sapiens/lib/python3.10/site-packages/mmpose/datasets/datasets/body3d/../../../../mmpretrain/models/backbones/vision_transformer.py", line 271, in __init__
    assert arch in set(self.arch_zoo), \
AssertionError: Arch sapiens_0.3b is not in default archs {'b', 'dinov2-giant', 'eva-g', 'deit-t', 'dinov2-s', 'large', 'dinov2-small', 'deit-tiny', 'dinov2-g', 'l', 'deit-small', 'deit-base', 'deit-b', 'base', 'eva-giant', 'deit-s', 'huge', 'small', 'h', 's'}`

I suppose this is an issue that the custom mmpose you provide only looks for the standard architectures. Also, I see "body3d" in the path, where I am only doing 2D pose with 17 keypoints. Can you give me a hint how to resolve this?
Thank you!

**Comment by rawalkhirodkar** [comment]
@ysuter you have mmpretrain already installed.
Please uninstall it and install the modules provided with the repo from source (instructions in _install/conda.sh).
