### ISSUE TITLE
Parsing performance

### ISSUE THREAD

**Issue by caiqi** [facebookresearch/sapiens#13]
The SAPIENS human parsing model is better than other open-source models, but it still exhibits noticeable errors, which seem unexpected for a model of 2B size. I think it may stem from the semantic segmentation approach and treat each pixel as a classification task. 
![image (8)](https://github.com/user-attachments/assets/a7529831-2c47-4ea5-8bf9-e600811e87b7)

Have you considered training an instance segmentation model specifically for the human parsing task? It might improve the quality and accuracy of the model's outputs. I have tested with SAM, it works well to generate good quality masks though it does not know human part information. 
![image](https://github.com/user-attachments/assets/9ae9e5b6-bbfe-4f50-9d59-991885df6994)

**Comment by rawalkhirodkar** [comment]
@caiqi thank you for pointing this out. We are investigating Sapiens-2B seg performance (likely the checkpoints got corrupted). Hoping to have an update on this soon. 

Till then please use Sapiens-1B seg, this should result in better generalization.

**Comment by caiqi** [comment]
Thanks. 1B seg seems have similar easy noticeable errors and many holes.
![image](https://github.com/user-attachments/assets/84b1bf42-820d-4f1e-9e83-dbc698e36a5e)

**Comment by rawalkhirodkar** [comment]
@caiqi As mentioned [here](https://github.com/facebookresearch/sapiens/issues/8), loose clothing like skirts is out-of-distribution for our segmentation models. The models are trained on body-tight clothing with a clear separation between upper and lower apparel (eg. tshirt + pants).

We are working on expanding our annotation set to include more clothing in the future.
