### ISSUE TITLE
Encountered an error running "bfloat16"

### ISSUE THREAD

**Issue by chen123hao** [facebookresearch/sapiens#133]
When running "lite/scripts/demo/bfloat/pose_keypoints308.sh", it gets stuck during the tqdm progress bar. 
When setting the detection config and checkpoint to None,"lite/scripts/demo/bfloat/pose_keypoints308.sh" can run, but it is slower, 
defeating the purpose of acceleration.
How can I correctly run the bfloat16 accelerated version?

**Comment by rawalkhirodkar** [comment]
@chen123hao sorry you are facing this issue. Can you explain what you mean by "but it is slower"? 
Specifically, "slower" compared to what?

**Comment by chen123hao** [comment]
> @chen123hao sorry you are facing this issue. Can you explain what you mean by "but it is slower"? Specifically, "slower" compared to what?

When setting the detection config and checkpoint to None : Running "lite/scripts/demo/bfloat/pose_keypoints308.sh" is slower than running "pose/scripts/demo/local/keypoints308.sh" possibly because of fewer input images and longer initialization time for the former. When the number of input images is 100, the former runs significantly faster than the latter.

However, setting the detection config and checkpoint to None leads to very inaccurate output results. May I ask what the approximate FPS is when you run the bfloat16 code normally?

**Comment by rawalkhirodkar** [comment]
@chen123hao the first inference with bfloat16 model is very slow due to auto-tune. The subsequent runs will be faster.
This is also mentioned in the readme: https://github.com/facebookresearch/sapiens/blob/main/lite/README.md

**Comment by chen123hao** [comment]
Thanks for reply.When running "lite/scripts/demo/bfloat/pose_keypoints308.sh", it gets stuck during the tqdm progress bar. How can I resolve this issue? I checked previous issues, and it was suggested to change from multiprocessing to sequential execution. Are there any other feasible solutions?If I only need the part of the 308 keypoints related to a specific area (such as the eye region), is there a faster way to run it?

**Comment by rawalkhirodkar** [comment]
@chen123hao if you are stuck on the tqdm bar for a long time, this suggests the incompatibility with parallelization. 
In this case, sequential processing will resolve the issue. You can also checkout the full-installation to resolve this.
