### ISSUE TITLE
Does visualiztion take a lot of time?

### ISSUE THREAD

**Issue by rabum** [facebookresearch/sapiens#134]
Can I turn it off to have faster procession? What part of code should I change

**Comment by rawalkhirodkar** [comment]
@rabum Yes ofcourse.
For example, if you are using pose: refer to this https://github.com/facebookresearch/sapiens/blob/7bd3594ccc98a64ffa40ce3d577eff6afa6efba7/lite/demo/vis_pose.py#L139

**Comment by rabum** [comment]
> @rabum Yes ofcourse. For example, if you are using pose: refer to this
> 
> https://github.com/facebookresearch/sapiens/blob/7bd3594ccc98a64ffa40ce3d577eff6afa6efba7/lite/demo/vis_pose.py#L139

I'm not using the lite version, the code in sapiens/pose/demo/demo_vis.py seems different, should I just set visualizer to None if I want to turn it off?

**Comment by rawalkhirodkar** [comment]
@rabum correct, setting visualizer to None will skip the vis.
https://github.com/facebookresearch/sapiens/blob/7bd3594ccc98a64ffa40ce3d577eff6afa6efba7/pose/demo/demo_vis.py#L64
