### ISSUE TITLE
segment inference requirement

### ISSUE THREAD

**Issue by a-drop-in-the-ocean456** [facebookresearch/sapiens#14]
does it necessary to install mmengine and mmseg, if necessary, what are the version of mmengine and mmseg?Thank you.

**Comment by rawalkhirodkar** [comment]
It is not. Please checkout [sapiens-lite](https://github.com/facebookresearch/sapiens/blob/main/lite/README.md).

**Comment by a-drop-in-the-ocean456** [comment]
After use export SAPIENS_LITE_ROOT=/path/to/sapiens-main/lite, when I use commend ./seg.sh, still No module named mmengine

**Comment by rawalkhirodkar** [comment]
Are you using https://github.com/facebookresearch/sapiens/blob/main/lite/scripts/demo/torchscript/seg.sh?

**Comment by a-drop-in-the-ocean456** [comment]
seg/scripts/demo/local/seg.sh

**Comment by rawalkhirodkar** [comment]
Please use the sapiens-lite inference scripts for torchscript. Refer [here]( https://github.com/facebookresearch/sapiens/blob/main/lite/scripts/demo/torchscript/seg.sh).
The one you are attempting to use currently are part of full-installation (requires mmengine).

**Comment by a-drop-in-the-ocean456** [comment]
ok, thank you.
