### ISSUE TITLE
AttributeError: module 'torch._inductor' has no attribute 'config'

### ISSUE THREAD

**Issue by thbdoux** [facebookresearch/sapiens#141]
I tried to run Pose estimation with _sapiens_lite_ `vis_pose.py` script on MacOS, and got this error : 

`Traceback (most recent call last):
  File "sapiens/lite/demo/vis_pose.py", line 485, in <module>
    main()
  File "sapiens/lite/demo/vis_pose.py", line 290, in main
    torch._inductor.config.force_fuse_int_mm_with_mul = True
AttributeError: module 'torch._inductor' has no attribute 'config'`

Torch version : 2.4.1

**Comment by rawalkhirodkar** [comment]
@thbdoux the code is tested with pytorch2.3 and 2.2 - can you please downgrade and try? 
I don't think the 2.3 -> 2.4 update might be an issue, other factor would be the MacOS environment. 
Please let us know.

**Comment by darkliang** [comment]
I am using torch 2.2.2 on CentOS 7 and encountered the same error. When I commented out the relevant code of `torch._inductor`, the program could run normally.

**Comment by rawalkhirodkar** [comment]
@darkliang thank you for the pointer. we will update the code to remove this torch inductor pointers.
