### ISSUE TITLE
Annotations and Evaluation

### ISSUE THREAD

**Issue by emilharutyunyaNN** [facebookresearch/sapiens#144]
Hi. I have tested the model with test.py with all the annotations and images. But the evaluation metric in the end is very low. I found out that it was because of the annotations in the validation set. I downloaded all the needed annotation files, and found out that for most images there is very few annotations present it is mostly 0.0 in the keypoints of the gt_instances. Did I download the wrong annotations or am I not supposed to run the test code with those?

**Comment by rawalkhirodkar** [comment]
@emilharutyunyaNN Hello, are you talking about pose model evaluation on the COCO dataset?

**Comment by emilharutyunyaNN** [comment]
yes, I have already solved the problem I filtered the annotations and the dataset, there was a format issue. Additionally I would like to ask, I would like to know how is COCO_val2017_detections_AP_H_70_person_new.json this obtained. I used it already, but I am trying to evaluate the model on OCHuman dataset, but it lacks a bouning box annotation file, I was wondering if it can be obtained some way or has to be manually made.

**Comment by rawalkhirodkar** [comment]
@emilharutyunyaNN we use an offshelf bounding box detector to get the json. You can try https://github.com/facebookresearch/detectron2.

On OCHuman dataset, you can also repurpose the ground-truth annotations or modify the testing code for evaluation.
