### ISSUE TITLE
Human detection before pose detection

### ISSUE THREAD

**Issue by rabum** [facebookresearch/sapiens#146]
What happens when the human detection model didn't detect all the humans in the image, will the pose model detect those undetected humans' body keypoints like when there's no det model used?

**Comment by rawalkhirodkar** [comment]
@rabum the pose model is top-down. That is we provide the detection bbox image crop as input.
In presence of no detection, the pose model will not be used.

**Comment by Jaykumaran** [comment]
Hello rabum,


I ve discussed the Sapiens on various downstream tasks in a article for LearnOpenCV, if you are interested do checkout for better understanding on how each task is being carried out.

https://learnopencv.com/sapiens-human-vision-models/


The code discussed in the article is based on a simple inference pipeline by https://github.com/ibaiGorordo/Sapiens-Pytorch-Inference


My fork with add ons: https://github.com/Jaykumaran/Sapiens-Pytorch-Inference
