### ISSUE TITLE
Inference time on nvidia V100 too long

### ISSUE THREAD

**Issue by rabum** [facebookresearch/sapiens#147]
When I used nvdia 4090 to run inference (not lite version ) the speed was around 0.4s per frame, then I changed to V100 it's around 1.3s per frame, what caused such big difference and how can I improve it?

**Comment by chopin1998** [comment]
V100 elder than 2080Ti,  vs 4090 ?

**Comment by rabum** [comment]
> V100 elder than 2080Ti, vs 4090 ?

The speed gap is no that big when I used yolo model, it's specifically big on the pose model, I wonder what causes it

**Comment by rawalkhirodkar** [comment]
@rabum the native model inference for pose is slow due to post-processing. The visualization and save to disk is very comprehensive and takes a while.
