### ISSUE TITLE
Question about input resolution

### ISSUE THREAD

**Issue by yk907** [facebookresearch/sapiens#153]
Thank you for your excellent work!

I am using your lite image encoder for my downstream task inference, and the image resolution in my dataset is only 448 * 224. When I am using the Lite version sapiens for inference, I report an error that the dimensions do not match. Do I have to use  a resolution of 1024 * 1024 for image encoding? Or do I need to install the full version of Sapiens or any suggestions? thanks.

**Comment by rawalkhirodkar** [comment]
@yk907 please do not update the input size, it corresponds to the model size.
Any size image will be resized to 1024 x 768 to support inference with Sapiens.

**Comment by limacv** [comment]
I wonder if the input image is in landscape mode (width > height), will resizing to portrait mode have negative effects on the model performance because of the distortion?
