### ISSUE TITLE
How to seg anime image?

### ISSUE THREAD

**Issue by ykj467422034** [facebookresearch/sapiens#156]
I want to segment the body parts of an image of an anime character.
However, even when using the 1b model in the demo, the effect is very poor. Are there any ways to segment the parts of an anime character? 
![Laura_main](https://github.com/user-attachments/assets/df03a225-77b9-4458-b95f-cbbaefdc81eb)
![img_v3_02g6_cfbffa90-13fc-44e4-9d4d-244d9858e63g](https://github.com/user-attachments/assets/1539265e-675b-4e02-a09b-bf5bd620bf6a)

**Comment by rawalkhirodkar** [comment]
@ykj467422034 unfortunately our models are only trained on natural images, performance on anime images is not guaranteed.

**Comment by ykj467422034** [comment]
@rawalkhirodkar Excuse me. Do you have a plan to train the segmentation model for anime?

**Comment by rawalkhirodkar** [comment]
@ykj467422034 No plans, unfortunately. 
It will be easy to finetune on the labels. However, the major issue is the lack of label data here.
