### ISSUE TITLE
2D Pose 133 points do not draw bones and keypoints

### ISSUE THREAD

**Issue by TonyDua** [facebookresearch/sapiens#157]
Hello, I am testing `pose/scripts/demo/local/keypoints133.sh` based on the guidance from this [https://github.com/facebookresearch/sapiens/blob/main/lite/docs/POSE_README.md](url). I modified the input, output, model file paths, etc., in `keypoints133.sh` according to my local setup. The png images in the output do not have any drawn skeletons or points, but the "keypoints" in the json file "instance_info" have values. What could be the issue? Thank you!

**Comment by rawalkhirodkar** [comment]
@TonyDua can you share an example image and the corresponding keypoint json to investigate the issue? Thanks.

**Comment by rawalkhirodkar** [comment]
@TonyDua closing the issue due to inactivity. Feel free to reopen.
