### ISSUE TITLE
tflite model

### ISSUE THREAD

**Issue by zstreet87** [facebookresearch/sapiens#158]
Hi there,

Thank you for this wonderful project! Is there any interest in releasing tflite format of the models for, perhaps, even smaller footprint?  Users could just convert to-from ONNX and then to tflite but that requires intimate knowledge of the model architecture so wanted to ask here.

**Comment by rawalkhirodkar** [comment]
@zstreet87 sorry there is no plan for tflite ports. We provide conversion scripts for torchscript, that might be a good reference to implement the tflite ports.
