### ISSUE TITLE
Input with two people grappling

### ISSUE THREAD

**Issue by lagondo** [facebookresearch/sapiens#162]
Hi, how well does the model work with two people grappling? See attached image.
![WhatsApp Image 2024-10-29 at 18 24 27](https://github.com/user-attachments/assets/4b6a9a92-5511-4288-9f58-ec51fd5cf51d)

**Comment by rawalkhirodkar** [comment]
@lagondo You can use our web demos to test the models: https://huggingface.co/collections/facebook/sapiens-66d22047daa6402d565cb2fc

**Comment by lagondo** [comment]
Thanks!
