### ISSUE TITLE
Asking about real-time performance

### ISSUE THREAD

**Issue by pvtoan** [facebookresearch/sapiens#165]
Hi, 

Firstly, thank you so much for your valuable contributions when publishing Sapiens.

Secondly, I would like to know if each of models in Sapiens, for example, segmentation, can run in real-time?

Because, when I run the seg_model (torchscript, 1b model), I obtained the result: FPS=0.73s
Besides, similar slow performances were also obtained when I test depth model.

However, when I see the demo in this link, the performance looks mostly like in real-time.

Could you please clarify this thing for me?

**Comment by rawalkhirodkar** [comment]
@pvtoan 1B model is about 2 to 4 FPS with optimizations - these optimizations are not currently part of this repository.
Sapiens-1B has significant number of FLOPs due to its high resolution, it is not real time.

Smaller backbones can be refurbhised for real time performance.

**Comment by pvtoan** [comment]
Hi @rawalkhirodkar,

In this current repository, is there any version suitable for real-time performance?
