### ISSUE TITLE
Asking about surface normal estimation

### ISSUE THREAD

**Issue by pvtoan** [facebookresearch/sapiens#166]
Hi, 

I saw that there is a code to get the surface normal from depth map in "vis_depth.py". 

So, what is the difference between this surface normal and another one obtained from "vis_normal.py"?

Thank you!

**Comment by rawalkhirodkar** [comment]
@pytoan normal from depth is only to illustrate the quality of the depth prediction.
Using the surface normal predictor is recommended if you are interested in normals.

**Comment by pvtoan** [comment]
Hi @rawalkhirodkar,

I got it.

Thank you!
