### ISSUE TITLE
Duplicate Detection: Repeated Pose Keypoints and Skeletons in Pose Estimation

### ISSUE THREAD

**Issue by Ody-trek** [facebookresearch/sapiens#167]
Hello, I encountered an issue with repeated detections while using Sapiens for human pose estimation. Regardless of whether I use the rtmdet_m_640-8xb32_coco-person.py (with NMS) or rtmdet_m_640-8xb32_coco-person_no_nms.py (without NMS) configuration file, the inference results always contain multiple overlapping detections of the same keypoints and skeletons.
![000000](https://github.com/user-attachments/assets/c022cac2-9f10-4db3-8a3c-530fe23d0e4e)

Testing Environment:
Input Data: pose/demo/data/itw_videos/reel1/
Configuration Files: Tried the following configurations, both yielding duplicate detections:
rtmdet_m_640-8xb32_coco-person.py (default with NMS enabled)
rtmdet_m_640-8xb32_coco-person_no_nms.py (with NMS explicitly disabled)
Inference Script: lite/scripts/demo/torchscript/pose_keypoints17.sh

Thank you for your help!

**Comment by rawalkhirodkar** [comment]
@Ody-trek did you make any other modifications? I am unable to reproduce this with the latest code on the repo.

**Comment by Ody-trek** [comment]
> @Ody-trek did you make any other modifications? I am unable to reproduce this with the latest code on the repo.

The issue has been resolved. It seems that the object detection model link provided on GitHub might be incorrect. I was able to get it working successfully by using a model from Hugging Face instead. Thanks!
