### ISSUE TITLE
is there any way to predict the visibility of each keypoint in pose?

### ISSUE THREAD

**Issue by xdfeng07** [facebookresearch/sapiens#17]
as I was browsing the codes, i found that [code](https://github.com/facebookresearch/sapiens/blob/5689659a8c16fbe5d1315cd3e0ab4a03e2cb8d9b/lite/demo/vis_pose.py#L136) here declares a keypoints_visible list, but just set all the values to be True. Maybe there are some ways to predict this list with the current model? As I found this model will always output keypoints for hands even when the hands are completely invisible in the image, is there any solution to avoid such cases?

**Comment by xdfeng07** [comment]
![image](https://github.com/user-attachments/assets/e92223ee-3081-4f08-ae92-5a80b6f75dde)
for exampe in this image, the model still outputs the hand keypoints although the hands are completely occluded by the torso

**Comment by xdfeng07** [comment]
and as i have noticed, for the keypoints invisible in the image, the model seems to be assigning them some random coordinates, so maybe the score should be enough

**Comment by xdfeng07** [comment]
and also I found that for the points invisible in the image, the model somehow tends to assign them random values, is there any possiblity that the model could give a prediction of coordinates outside the current canvas?

**Comment by affromero** [comment]
Do not quote me here, but as far as I am aware, the [COCO keypoint dataset](https://cocodataset.org/#keypoints-eval) does not provide the coordinates for those keypoints that are non-visible (at most you get this `[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 142, 309, 1, 177, 320, 2,...]` for `[xi,yi,vi]` - taken from the coco annotation json file), so most of the time this visibility flag is ignored in the training pipeline?
What you see as the visibility score here, I think you must take it as a probability that there is a keypoint in such position, which is not exactly the same as such keypoint being visible or not, although sometimes correlated.

**Comment by rawalkhirodkar** [comment]
Keypoint visibility can be inferred from the predicted keypoint score.

There is no explicit way to obtain visibility.
