### ISSUE TITLE
about Sapiens depth estimator setup

### ISSUE THREAD

**Issue by bbakpil** [facebookresearch/sapiens#173]
Hello, thanks for your awesome work!

I have some questions about the Sapiens depth estimator.

(1) I'm getting some negative values for the depth. Is this normal? (Face (head) images)
(2) When I unproject the image with the estimated depth (and the camera params), I'm getting kind of diffferent view compared to the input image. My guess is that the camera setting that I am using (3DGS) and that of Sapiens are not the same. So I want to check the focal length and the principal points. Are these setting in the code or the paper?

Thank you in advance!

**Comment by rawalkhirodkar** [comment]
@bbakpil Hello,

1. Negative values are unlikely but possible. We dont explictly restrict the range of neural network predictions.
2. Sapiens predict relative depth and not absolute depth. To unproject the image, you would need to recover the absolute depth. This needs estimating a scale and translation factor to convert rel to abs depth.

**Comment by bbakpil** [comment]
Thanks for your kind reply. So for 2., it means that I need to do something else to figure out the scale, translation factors?

**Comment by rawalkhirodkar** [comment]
Ofcourse @bbakpil 

Unfortunately yes, you can also offshelf absolute depth estimator to get the coarse depth and then align the sapiens depth to get the scale and offset.
