### ISSUE TITLE
question about detailed segmentation methods for body parts when wearing long clothing.

### ISSUE THREAD

**Issue by chojinie** [facebookresearch/sapiens#175]
> [!NOTE]
> Never been asked.

Hello Author.

Thanks for share nice work!
I have some questions.

On the human body part segmentation task, when wearing short sleeves, the forearm seems to be well segmented. However, when wearing long sleeves, the entire arm is segmented as part of the upper body clothing. Is this how it is typically handled in human parsing tasks? Is it not possible to segment the forearm and upper arm separately, even if clothing is worn?

The same question applies to the lower body as well.

Best Regards,

**Comment by rawalkhirodkar** [comment]
@chojinie Thank you for your interest in the project.

I think you are referring to under clothing segmentation. This is not commonly done in part segmentation as obtaining such annotations at scale is challenging and highly ambiguous.
