### ISSUE TITLE
Estimating metric depth with known camera parameters

### ISSUE THREAD

**Issue by chunjins** [facebookresearch/sapiens#178]
Thanks for the great work! I was wondering if you have any suggestions for converting relative depth to metric depth when I have the ground truth camera intrinsics and extrinsics, or even the SMPL mesh for the human body? Any ideas are welcome. :)

**Comment by rawalkhirodkar** [comment]
@chunjins using the SMPL mesh you can obtain the coarse metric depth.
You can then align the relative depth to the metric depth by solving for scale and shift (for all pixels corresp to SMPL mesh):

(1. / metric_depth) = shift + (scale * output) to compute the scale and shift via lstsq, and get the metric by 1. / (shift + (scale * output)). The output is Sapiens rel depth.

**Comment by chunjins** [comment]
Thank you for the helpful suggestion.
