### ISSUE TITLE
Running the pose estimator in windows

### ISSUE THREAD

**Issue by IsabelCanicoNeto** [facebookresearch/sapiens#179]
Hi
We are having problems running the pose estimator in windows. We used **extract_features.py** to launch the inference and we are using **lite version**. 

We  are trying to do pose estimation: https://github.com/facebookresearch/sapiens/blob/main/lite/docs/POSE_README.md
We had some issues installing the BBox detector, so skipped it for now and tried to run inference on the full image as mentioned in the link above. But we are running on Windows and are trying to use the available models [ models: (https://huggingface.co/facebook/sapiens-pose-0.3b-torchscript, 0.6b and 1b),  to run inference. 

We are getting some pytorch errors after specifying the size of the input image.
**for model 0.3b and 0.6b** RuntimeError: The size of tensor a (950) must match the size of tensor b (3072) at non-singleton dimension 1

**for model 1b** RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

How can we solve this to use the three possible models. 

Here is the command we are using for model 1b as an example : 

`python C:\sapiens\lite\demo\extract_feature.py C:\sapiens_lite_host\torchscript\pose\checkpoints\sapiens-pose-1b-torchscript\sapiens_1b_goliath_best_goliath_AP_639_torchscript.pt2 --input C:\videos\sapiensinput  --output-root C:\videos\sapiensoutput --shape 612 408` 

thanks

**Comment by rawalkhirodkar** [comment]
@IsabelCanicoNeto I see that you are using the wrong python file for pose estimation.
Please use ``` C:\sapiens\lite\demo\vis_pose.py``` instead: [reference](https://github.com/facebookresearch/sapiens/blob/08dce797f7b40f5b41388f518cac85535c3f5d13/lite/scripts/demo/torchscript/pose_keypoints308.sh#L31).

Additionally, please do not provide the ```--shape``` argument, the model input resolution is fixed to 1024 x 768. Your images will be automatically resized. Please mimic [this](https://github.com/facebookresearch/sapiens/blob/08dce797f7b40f5b41388f518cac85535c3f5d13/lite/scripts/demo/torchscript/pose_keypoints308.sh#L79).

**Comment by IsabelCanicoNeto** [comment]
Thank you I have tested using the command

python C:\sapiens\lite\demo\vis_pose.py C:\sapiens_lite_host\torchscript\pose\checkpoints\sapiens-pose-0.6b-torchscript\sapiens_0.6b_goliath_best_goliath_AP_609_torchscript.pt2 --input C:\videos\sapiensinput  --output-root C:\videos\sapiensoutput

Now it seems I have a memory problem. 
RuntimeError: CUDA out of memory. Tried to allocate 6.75 GiB. GPU 0 has a total capacity of 8.00 GiB of which 0 bytes is free. Of the allocated memory 9.71 GiB is allocated by PyTorch, and 64.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)


thanks for your support

**Comment by rawalkhirodkar** [comment]
@IsabelCanicoNeto please use the batch size flag to set a smaller batch size.

**Comment by IsabelCanicoNeto** [comment]
Hi there

I was able to run it, and get inference. but the output is a json file (different from the one gathered on the web).  (see the file )
[image_from_vid_pose.json](https://github.com/user-attachments/files/18049125/image_from_vid_pose.json)
[sameimage_fromweb.json](https://github.com/user-attachments/files/18049127/sameimage_fromweb.json)
 

Also **no image was created** and the vis_pose.py produced a warning/error like this "img_save_and_vis
`    raise ValueError(ValueError: the length of kpt_color (133) does not matches that of keypoints (308)"`

Can you also help in other things please :
1. The vis_pose.py took 68s to inference one picture ... which is kind of slow for only one picture, is it normal? 
2. how can I add a video as input to track the pose changes during the video ? Any need for prepocessing the video ? 
3. I want to add a webcamera to stream in real-life and track the poses along the way, is there an option in sapiens for it? 
Thanks in advance

**Comment by rawalkhirodkar** [comment]
@IsabelCanicoNeto The command is still not mimicking our demo script. 
I see that you are using a 308 kps estimator. Please set the ```--num_keypoints``` as 308 [refer](https://github.com/facebookresearch/sapiens/blob/08dce797f7b40f5b41388f518cac85535c3f5d13/lite/scripts/demo/torchscript/pose_keypoints308.sh#L81).

1. 68s per image is not normal. Its difficult to say what could be causing this. Sapiens-1B model is roughly 1 image per second. The major bottleneck here is visualizing the keypoints on the image. 308 kps takes a while. You can turn off the visualization if you only intend to use the jsons.

2. No preprocessing required for the video. Simply extract frames into a folder and provide the folder path as input.

3. On the webcam mode, please refer to [issue](https://github.com/facebookresearch/sapiens/issues/91).

**Comment by IsabelCanicoNeto** [comment]
Thanks for that

1. Using the num_keypoints make it faster (38s, which is a lot for one picture, and does not collect the different persons in the frame), see attached. Also the json is not identifing the body parts. 

2. Also I was trying to get the 1B model running with the command

`python C:\sapiens\lite\demo\vis_pose.py C:\sapiens_lite_host\torchscript\pose\checkpoints\sapiens-pose-1b-torchscript\sapiens_1b_goliath_best_goliath_AP_639_torchscript.pt2 --input C:\videos\sapiensinput  --output-root C:\sapiensoutput --batch_size 10 --num_keypoints 308`

but still raise the error "RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory"

3. Lastly when I try to install det from my PC, it raises a problem on meta.py file 
   
  
>    File "<string>", line 17, in <module>
>       ModuleNotFoundError: No module named 'torch'
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build editable did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> 

Thanks for all your support 

[image_from_vid_pose2.json](https://github.com/user-attachments/files/18050140/image_from_vid_pose2.json)
![image_from_vid_pose2](https://github.com/user-attachments/assets/1c3f128b-1608-45a0-93d4-1a78154c80d5)
