### ISSUE TITLE
Commercial license

### ISSUE THREAD

**Issue by spiegelball** [facebookresearch/sapiens#18]
Is it possible to obtain a commercial license?

**Comment by rawalkhirodkar** [comment]
Unfortunately, no as of now.

**Comment by spiegelball** [comment]
Thank you for the reply. Is there anything planned in this direction or do you have the contact of someone I could speak to about it?

**Comment by rawalkhirodkar** [comment]
@spiegelball This is not planned. We do not have a point of contact about this. 

If there are any updates on the change of license, we will modify the github repo to reflect it.
