### ISSUE TITLE
Request for Evaluation Code/Steps for Semantic Segmentation, Depth Maps, and Normal Maps.

### ISSUE THREAD

**Issue by Hermine-D** [facebookresearch/sapiens#180]
The README does not provide specific guidance or code for evaluating semantic segmentation, depth maps, and normal maps. Could you kindly provide the code or script to evaluate semantic segmentation, depth maps, and normal maps? Or a step-by-step guide or detailed instructions on how to conduct these evaluations. Thank you very much!
![image](https://github.com/user-attachments/assets/1570f686-eebf-4fec-8c29-1096df020499)

**Comment by rawalkhirodkar** [comment]
@Hermine-D unfortunately the evaluation set for segmentation is not public.
For depth and normal, we evaluate on Hi4D and Thuman2.0 scans by rendering them using virtual cameras.
Due to license restrictions, we cannot share the derived assets used for evaluation.
