### ISSUE TITLE
Depth evaluation metrics

### ISSUE THREAD

**Issue by fatemeh-slh** [facebookresearch/sapiens#181]
Hi,

Thanks for the great work.
I have a question regarding depth evaluation. As the depth values are valid only for the human mask, I was wondering for computing metrics such as AbsRel, the averaging has been done on the entire image or only on the valid mask?

Thanks.

**Comment by rawalkhirodkar** [comment]
@fatemeh-slh thank you for your interest. All metrics are computed only on human pixels.
