### ISSUE TITLE
Failed in in-the-wild image

### ISSUE THREAD

**Issue by hygenie1228** [facebookresearch/sapiens#182]
Hi @rawalkhirodkar ,
Thank you very much for your hard work.
I also faced the problem of segmentation lite not working well.

I read the Github issue, I'm still having issues even though I'm selecting high resolution images and doing foreground segmentation.
Doesn't this work well for in-the-wild images?

<img width="517" alt="image" src="https://github.com/user-attachments/assets/1426252d-0885-4437-ac19-8bd011d06155" />

<img width="533" alt="image" src="https://github.com/user-attachments/assets/e695cb9d-9318-4aad-a2d8-4b116088d01f" />

**Comment by rawalkhirodkar** [comment]
@hygenie1228 you may want to increase the backbone size for better generalization. This is the result of the 1B model.
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/83fa3552-9402-4627-aaba-8e06e7d3049a" />
