### ISSUE TITLE
conda environment destroyed

### ISSUE THREAD

**Issue by robotNo201** [facebookresearch/sapiens#188]
don't do not run the code. my ubuntu wsl2 completely get destroyed. I hope the team can come out and explain everything. I mean, if you guys can't manage the environment, don't post it to harm others please

**Comment by robotNo201** [comment]
I have so many projects setup on virtual environment, and you destroy the whole thing, bro, just put your trash down from the github, can you?

**Comment by robotNo201** [comment]
I haven't see so unprofessional coder on github, when i enter any conda command now, i get urllib3 error

**Comment by robotNo201** [comment]
I believe people will understand me, as a developer in a company, i will try my best to request a retrieval on your paper, this code is not right, is not prepared, and further, it destroys companies' environment, it is security issue.

**Comment by una-dinosauria** [comment]
Sorry you experienced issues @robotNo201. You are welcome to not use the code anymore.
