### ISSUE TITLE
[ModuleNotFoundError: No module named 'mmcv._ext']

### ISSUE THREAD

**Issue by davidrs** [facebookresearch/sapiens#25]
Super excited to try out the segmentation model, but I'm failing to get it working. I keep hitting: 
`[ModuleNotFoundError: No module named 'mmcv._ext']`
I believe its an MMCV version or compatibility issue (people hit this error for various reasons over the last 4 years)
https://github.com/open-mmlab/mmdetection/issues/3271

All the recent fixes involve getting on latest mmcv, which you can't do for mmsegmentation since it doesn't support`mmcv==2.2.0`

I'm on a linux system that does not support conda. I tried to get my poetry deps to line up with versions in requirements.

1. Anyone else experience and resolve this issue?
2. A demo colab notebook would be amazing if someone can set one up to be able to quickly try it out in an interactive way and alleviate a lot of this specific env setup pain for quick experimentation.

**Comment by davidrs** [comment]
fwiw I see from this users demo many of those depencies aren't actually needed for a quick inference experiment:

https://huggingface.co/spaces/joselobenitezg/sapiens-demo/blob/main/inference/seg.py

demo dir is very robust. but may be worth a version that is minimal viable inference

**Comment by rawalkhirodkar** [comment]
@davidrs 
Option 1: Install from source. Refer [here](https://github.com/facebookresearch/sapiens/blob/main/_install/conda.sh).
Option 2: Use the lite inference (only pytorch needed). Refer [here](https://github.com/facebookresearch/sapiens/tree/main/lite).

Let me know if this works for you. We are working on hugging-face demo - coming soon!

**Comment by jcjackch** [comment]
Hi @rawalkhirodkar ,
Thanks for your tips. I tried to install the full model with Option1, but this error still exists to me.
I noticed that when I build the cv folder, it already says Skip building ext ops due to the absence of torch.

**Comment by jcjackch** [comment]
it seems like I needed to install cudatoolkit 12.1 and then re-compile sapiens-cv to install mmcv ext

**Comment by davidrs** [comment]
@rawalkhirodkar  thank you, i'd accidentally pulled the wrong demo file originally, which is why it was requiring mmengine etc. Thanks for the pointer t the `lite` demo. getting further now.

I can open a new issue but it appears demo will error if device=cpu because it has a `.cuda` call that will fail

**Comment by rawalkhirodkar** [comment]
@davidrs great!
Yes, all inferences require a gpu currently. CPU only support is not planned.

**Comment by davidrs** [comment]
ahh that's unfortunate. I'll try GPU first to get it all working then see if i can get CPU up.

On saved out images I'm seeing `blue people`. This means the color channels are not in the correct order.

this line converts from RGB to BGR, which normally fixes blue people. So to me it implies its expecring RGB, but the data loader is not converting to RGB. So i think there is a bug in the expected color channels
https://github.com/facebookresearch/sapiens/blob/main/lite/demo/vis_seg.py#L119

**Comment by rawalkhirodkar** [comment]
Can you share your image? Are you giving images as input from disk or modifying the code for inference?

We use cv2 to read images in bgr - this is the input to the inference_model function.

**Comment by davidrs** [comment]
Then it sounds like the images are never in RGB and the RGBtoBGR conversion should be dropped in 
https://github.com/facebookresearch/sapiens/blob/main/lite/demo/vis_seg.py#L119

I'm running the demo script unedited apart from one line to drop `.cuda()` so it works on CPU.

Example image:
![image](https://github.com/user-attachments/assets/acbef4ee-8a59-4777-868d-46efc7572bac)

**Comment by davidrs** [comment]
If i drop the conversion line I get expected behaviour:
![image](https://github.com/user-attachments/assets/2beb1964-efcd-44e3-be00-1b709ef26208)

**Comment by rawalkhirodkar** [comment]
@davidrs The bluish color in segmentation is due to the background class given a blue neutral color. Behavior 1 (with no code modification) is the expected result. 

You can change the color palette for background class according to your needs.

We convert images from bgr to rgb inside the model forward.

**Comment by davidrs** [comment]
ok, thanks for clarifying!

**Comment by davidrs** [comment]
although in the demo pages and example images it looks like you are not doing that conversion and/or are filtering out background. mask. May want to consider udpating demo to align with demo visuals used elsewhere: 
![image](https://github.com/user-attachments/assets/eb92e236-4716-41c8-a679-adfff421332c)
![image](https://github.com/user-attachments/assets/3722e9d3-b98f-44df-979c-65f5287e875b)

**Comment by rawalkhirodkar** [comment]
@davidrs Fixed now: [refer](https://github.com/facebookresearch/sapiens/blob/0b2e0171a65cc0bc58f86632d74e118013e19df9/lite/demo/vis_seg.py#L115). Thank you for flagging this.
