### ISSUE TITLE
Can you publish the onnx model?

### ISSUE THREAD

**Issue by juntaosun** [facebookresearch/sapiens#28]
Can you release the onnx model?
onnx is very convenient for inference and acceleration, this project is exciting!

**Comment by Kaustubh-cpu** [comment]
hey @juntaosun 
Is this code running for segmentation ?

**Comment by rawalkhirodkar** [comment]
@juntaosun we provide torchscript models for inference. Onnx models are part of the roadmap.

**Comment by rawalkhirodkar** [comment]
@juntaosun please find the onnx models: https://huggingface.co/onnx-community/sapiens-normal-0.3b
