### ISSUE TITLE
Please install mmdet for sapiens_lite

### ISSUE THREAD

**Issue by fzoric8** [facebookresearch/sapiens#31]
Hi, 

I'm trying to run sapiens_lite, more concretely 
`pose_keypoints17.sh` from `sapiens/lite/scripts/demo/torchscript`. 

I've built `sapiens_lite` conda env as recommended. 

But after configuring correct weights (`$CHECKPOINT` env variable), after running `pose_keypoints17.sh` I get following output: 
```
Traceback (most recent call last):
  File "/root/sapiens/lite/demo/vis_pose.py", line 459, in <module>
    main()
  File "/root/sapiens/lite/demo/vis_pose.py", line 249, in main
    assert has_mmdet, "Please install mmdet to run the demo."
AssertionError: Please install mmdet to run the demo.
```
After running `pip install mmdet` which install succesfuly, when typing: 
```
import mmdet
```

I get: `please install mmcv`. 

From `pose_keypoints17.sh` I can infer that `RTMDet` is used for the object detection (which is I suspect part that requires mmdet, and mmcv), however I'm not sure how to turn it off, and maybe completely mitigate object detector? 

If I remove env vars for detector I get following: 
```
vis_pose.py: error: argument --det-config: expected one argument
```

My question is, how can I use `sapiens_lite` without `mmdet` and where are the weights for the `lite` option :) 

Thanks.

**Comment by rawalkhirodkar** [comment]
You have to trigger this condition https://github.com/facebookresearch/sapiens/blob/main/lite%2Fdemo%2Fvis_pose.py#L245. 

Removing det config and det checkpoint from arguments in shell will do it.
