### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kaustubh-cpu** [facebookresearch/sapiens#32]
ImportError: Failed to import custom modules from {'imports': ['mmseg.engine.optimizers.layer_decay_optim_wrapper'], 'allow_failed_imports': False}, the current sys.path is:
    C:\Users\ml2au\sapiens\sapiens\seg\demo
    C:\Users\ml2au\AppData\Local\Programs\Python\Python39\python39.zip
    C:\Users\ml2au\AppData\Local\Programs\Python\Python39\DLLs
    C:\Users\ml2au\AppData\Local\Programs\Python\Python39\lib
    C:\Users\ml2au\AppData\Local\Programs\Python\Python39
    C:\Users\ml2au\sapiens\myvenv
    C:\Users\ml2au\sapiens\myvenv\lib\site-packages
    c:\users\ml2au\sapiens\myvenv\src\taming-transformers
    c:\users\ml2au\sapiens\myvenv\src\latent-diffusion
    c:\users\ml2au\sapiens\myvenv\src\clip
    c:\users\ml2au\sapiens\sapiens\engine
    c:\users\ml2au\sapiens\sapiens\cv
    c:\users\ml2au\sapiens\sapiens\pretrain
    c:\users\ml2au\sapiens\sapiens\pose
    c:\users\ml2au\sapiens\sapiens\det
    c:\users\ml2au\sapiens\sapiens\seg
    C:\Users\ml2au\sapiens\sapiens\seg\demo
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

Getting this error in almost 2 to 3 code files

**Comment by rawalkhirodkar** [comment]
@Kaustubh-cpu did you install the packages as editable (pip install -e)? This should not happen in that case.

**Comment by Kaustubh-cpu** [comment]
Thankyou so much for your quick response @rawalkhirodkar ..i have solved that particular error successfully .............. and also great work @rawalkhirodkar 

Just wanted to know if i am using (sapiens_0.3b_goliath_best_goliath_mIoU_7673_epoch_194) checkpoint ......... what changes i have to make in seg.sh file for Inference on the image.....

**Comment by rawalkhirodkar** [comment]
@Kaustubh-cpu great!
Simply change the model name and checkpoint path in seg.sh.

**Comment by 0LEL0** [comment]
How do you solve this problem? I am troubled in the same place.

**Comment by omkaar718** [comment]
How was this issue solved? The packages were installed as editable (pip install -e).
