### ISSUE TITLE
Lite Demos ignores opacity arg

### ISSUE THREAD

**Issue by davidrs** [facebookresearch/sapiens#33]
Demo script for segmentation does not properly use opacity arg.

The bug is that here:
https://github.com/facebookresearch/sapiens/blob/main/lite/demo/vis_seg.py#L246

The list of params is missing a `threshold` arg that `img_save_and_viz` expects
so then the `title` is used as the `threshold` and the `opacity` is used as the `title`.

Fix is to add a threshold value in to the list of args so they properly line up with  `img_save_and_viz`

**Comment by rawalkhirodkar** [comment]
@davidrs Thank you for pointing this out. Fixed in recent commit.
