### ISSUE TITLE
mmcv Error

### ISSUE THREAD

**Issue by Kaustubh-cpu** [facebookresearch/sapiens#37]
@rawalkhirodkar 

I am facing the issue in the model path ................. 
MODEL_NAME='sapiens_0.3b'; [ CHECKPOINT=$SAPIENS_CHECKPOINT_ROOT/seg/checkpoints/sapiens_0.3b/sapiens_0.3b_goliath_best_goliath_mIoU_7673_epoch_194_$MODE.pt2 ]

As i have created the folder of checkpoint  inside seg ..............but because of MODE path is getting change
(SAPIENS_CHECKPOINT_ROOT=$SAPIENS_CHECKPOINT_ROOT/$MODE)

**Comment by rawalkhirodkar** [comment]
@Kaustubh-cpu please use the instructions and scripts from [here](https://github.com/facebookresearch/sapiens/tree/main/lite).

The scripts should automatically set the $MODE (I am guessing you are using torchscript?).
