### ISSUE TITLE
Depth Loss

### ISSUE THREAD

**Issue by kkaytekin** [facebookresearch/sapiens#38]
Hello,
in the paper, in page 5, the equation 3 is referenced to 32: "Depth map prediction from a single image using a multi-scale deep network" from Eigen et. al. . But looking at this reference couldn't answer the following: 

What is the reason to put the loss term in a square root there? 

Sum of squares will always be $\geq$ square of sums, so the square root in this formulation will always be safe to use, but what is the underlying reason to do so?

Best regards,

**Comment by rawalkhirodkar** [comment]
Great question - I had a similar one for silog loss.
Please read this [article](https://hiddenlayers.tech/blog/the-mystery-of-silog-loss/) for the explanation.
