### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by a-drop-in-the-ocean456** [facebookresearch/sapiens#4]
this is a great job, I am very interested with dataset, but do not found, is it public available.

**Comment by rawalkhirodkar** [comment]
Thank you. Datasets are proprietary and are not public.

**Comment by ShulingTang** [comment]
> Thank you. Datasets are proprietary and are not public.

Thank for your work. I wonder how much data was used in the SEG model training?

**Comment by pablovela5620** [comment]
@rawalkhirodkar  I realize that it's unlikely that the human-300m dataset will be open-sourced, but I wanted to ask if there were any plans for the photogrammetry/synthetic dataset described here. This would be super beneficial for the community to push forward human depth/normal estimation!

<img width="606" alt="image" src="https://github.com/user-attachments/assets/77e2e8c6-dff3-4bc1-a92b-4d96a6444265">
