### ISSUE TITLE
seg lite error

### ISSUE THREAD

**Issue by swzparker7** [facebookresearch/sapiens#41]
The result of my using the seg command “python vis_seg.py ./sapiens_lite_host/torchscript/seg/checkpoints/sapiens_0.6b/sapiens_0.6b_goliath_best_goliath_mIoU_7777_epoch_178_torchscript.pt2 --input ../data/frames/XDmfBTgIRUg_9 --batch-size=8 --output-root=../data/seg/XDmfBTgIRUg_9” is as follows, the image is not semantically segmented:
![image](https://github.com/user-attachments/assets/4e76ca2d-c06b-46d2-abb4-92f6c1cfa32a)
![image](https://github.com/user-attachments/assets/539e4920-a469-4d6a-8a51-a93407336ac0)

and if I execute the depth command again, the error will be reported as follows:
**[ERROR/ForkPoolWorker-3] Traceback (most recent call last):
  File "/mnt/local6T/wangzheng/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/mnt/local6T/wangzheng/sapiens/lite/demo/vis_depth.py", line 131, in img_save_and_viz
    (depth_foreground - min_val) / (max_val - min_val)
UnboundLocalError: local variable 'min_val' referenced before assignment**

I further modified my seg command by adding --shape "--shape 512",but he reported an error “**RuntimeError: The size of tensor a (1024) must match the size of tensor b (3072) at non-singleton dimension 1**” 

I would like to ask if it is only possible to detect the whole body with the head and not the single head. Looking forward to your reply, will be very helpful to me. Thank you for your time.

**Comment by swzparker7** [comment]
PS: Running the example data pose/data/reel1 with the above command is able to segment and estimate properly, so I wonder whether or not there are limitations on detection image.

**Comment by rawalkhirodkar** [comment]
Hello, in these two images, the segmentation prediction does not contain any foreground class.

We use this foreground mask to normalize the depth prediction in 0 to 1 to visualize. 

This is the reason for the crash on your examples. 

Why does the segmentation not work on these images?: my guess is the original resolution of these two images is much smaller than 1024×768, this results in a blurry upsampling and the network thinks it's part of the background.

**Comment by GloryyrolG** [comment]
> Hello, in these two images, the segmentation prediction does not contain any foreground class.
> 
> We use this foreground mask to normalize the depth prediction in 0 to 1 to visualize.
> 
> This is the reason for the crash on your examples.
> 
> Why does the segmentation not work on these images?: my guess is the original resolution of these two images is much smaller than 1024×768, this results in a blurry upsampling and the network thinks it's part of the background.

Hi @rawalkhirodkar ,

may I ask to clarify if it means segmentation is more important than depth estimation, etc.? according to the demo, once it does not segment the person, depth estimation makes no sense. thx & best,

**Comment by hygenie1228** [comment]
Hi @rawalkhirodkar ,
Thank you very much for your hard work.
I also faced the problem of segmentation lite not working well.

I read the Github issue, I'm still having issues even though I'm selecting high resolution images and doing foreground segmentation.
Doesn't this work well for in-the-wild images?

<img width="517" alt="image" src="https://github.com/user-attachments/assets/1426252d-0885-4437-ac19-8bd011d06155" />



<img width="533" alt="image" src="https://github.com/user-attachments/assets/e695cb9d-9318-4aad-a2d8-4b116088d01f" />
