### ISSUE TITLE
After running the pose_keypoints308.sh script under the lite environment, it gets stuck

### ISSUE THREAD

**Issue by qinsee** [facebookresearch/sapiens#42]
After running the pose_keypoints308.sh script under the lite environment, it gets stuck at "Loads checkpoint by local backend from path: /root/workspace/check/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth" and the progress bar remains stationary displaying "??" 。conda.sh already run

**Comment by qinsee** [comment]
![Uploading 1725006731663.jpg…]()

**Comment by rawalkhirodkar** [comment]
Yes, removing bbox detector will help.
Otherwise please consider upgrading pytorch to 2.2+

**Comment by yuchenli-sony** [comment]
I come across the same issues

**Comment by yuchenli-sony** [comment]
my pytorch is 2.2 cuda is 12.1 but it doesn't fix

**Comment by yuchenli-sony** [comment]
I fix the problem after I delete it

**Comment by Dratlan** [comment]
> I fix the problem after I delete it

hey, how  do you fix it? by remove the --det-config and --det-checkpoint？my torch is 2.3.1

**Comment by tuonisitake** [comment]
> > I fix the problem after I delete it
> 
> hey, how do you fix it? by remove the --det-config and --det-checkpoint？my torch is 2.3.1

remove the --det-config and --det-checkpoint in file pose_keypoints17.sh can work!

Distributing 100 image paths into 1 jobs.
100%|█████████████████████████████████████████████████████████████████| 13/13 [00:39<00:00,  3.06s/it]
Total inference time: 41.38 seconds. FPS: 2.42
/home/ubuntu/newdisk1/PythonProjects/sapiens-main/lite/scripts/demo/torchscript
Processing complete.
Results saved to /home/ubuntu/newdisk1/PythonProjects/sapiens-main/Outputs/vis/itw_videos/reel1/sapiens_1b
