### ISSUE TITLE
Continue Pretraining Sapiens to custom data

### ISSUE THREAD

**Issue by pablovela5620** [facebookresearch/sapiens#44]
If I have a specific data distribution (such as workout images/videos) is it possible to continue the pertaining process to better fit my domain? I found something similar for DinoV2 https://github.com/facebookresearch/dinov2/issues/204 but it seems that's not the case for them. I'm also interested in this to see if its possible to extend the encoder to the multiview domain like [crocov2](https://github.com/naver/croco) or [Croco-man](https://europe.naverlabs.com/research/publications-enhanced/cross-view-and-cross-pose-completion-for-3d-human-understanding/)

**Comment by rawalkhirodkar** [comment]
@pablovela5620 yes, you can continue pretraining using the training configs [here](https://github.com/facebookresearch/sapiens/tree/main/pretrain/configs/sapiens_mae/humans_300m_test).
How to kickstart the pretraining using the config: [refer here](https://mmpretrain.readthedocs.io/en/latest/user_guides/train.html).

These are all external pointers. We will make it easy to do this soon with the repository in upcoming updates.

**Comment by pablovela5620** [comment]
Fantastic, thank you for the quick response. I'll take a look through these, awesome to see ya'll using OpenMMLab repos so extensively! Look forward to the coming updates
