### ISSUE TITLE
Dependency Issues with Sapiens Lite (Pose Task) - Documentation Update Request

### ISSUE THREAD

**Issue by gabriellanzer** [facebookresearch/sapiens#45]
# MMDET and MMCV Dependencies
When trying to run the Sapiens Lite pose script (\lite\scripts\demo\torchscript\pose_keypoints308.sh) I had a few dependency issues that could be better documented. Even after installing mmdet `vis_pose.py` kept saying it wasn't installed. The try-catch block doesn't forward console errors so you don't know what's going wrong until you run the lines yourself.

Essentially, I was missing mmcv. While trying to install that, I had to downgrade numpy (<2.0) otherwise it would have issues. After that, I realized I was missing CUDA Toolkit and CUDA Runtime Native Libraries (cudart) so mmcv wouldn't install properly. They also have to match pytorch version, of course. Once I got it to run, I got an error saying that I should install an older version of mmcv, as 2.2.0 was incompatible.

So after a few hours of messing around, I finally don't get any errors (but I am adjusting the script paths now, so let's see if there will be any surprises). Since this is the Lite version, I thought it would be easier to set up. Could you update the read-me so the installation steps cover these dependencies? If I have some time, I will make a new conda environment and run through the setup steps again to find an optimal install script (and update this issue/make a pull request).

Many thanks! And I appreciate the amazing work and effort you are putting into this, and making it all open source.

**Comment by gabriellanzer** [comment]
It seems to be stuck at this stage... Not sure what's going on:
![image](https://github.com/user-attachments/assets/b3118924-add8-4f8a-a771-bde758ca92be)

**Comment by gabriellanzer** [comment]
Removing the detector lines as mentioned in the readme makes it budge. Results seem to have degraded quality though...
![000088](https://github.com/user-attachments/assets/67cc5870-4d71-4024-ade4-28ecd07194ce)

**Comment by mkemka** [comment]
Can you run the pose models from the source mmdet repo? https://github.com/open-mmlab/mmdetection

**Comment by rawalkhirodkar** [comment]
@gabriellanzer Sorry about your troubles with the lite-pose inference.
The easiest way to install the detector is to install from source the packages in the repo - they are version compatible and this ensures you dont run into pytorch/numpy inconsistencies.

```
export SAPIENS_ROOT=/path/to/sapiens
cd $SAPIENS_ROOT/engine; pip install -e .
cd $SAPIENS_ROOT/cv; pip install -e .
cd $SAPIENS_ROOT/det; pip install -e .
```

I will update the documentation with this pointer.
