### ISSUE TITLE
arch sapiens2b is not in default arch 

### ISSUE THREAD

**Issue by Yunnnnqiiiii** [facebookresearch/sapiens#46]
Thanks for your work！ I meet a problem and don't know how to solve it，can you help me?
![微信图片_20240831160817](https://github.com/user-attachments/assets/9ed86964-42e4-4cca-9d3a-da76a35ad3a8)

**Comment by rawalkhirodkar** [comment]
Hello, looks like the pretrain module is not correctly installed.

Did you try cd $SAPIENS_ROOT/pretrain; pip install -e . ?

If yes, please uninstall the current mmpretrain packge - this might be conflict.

**Comment by thechillday1** [comment]
🩸👍

**Comment by Yunnnnqiiiii** [comment]
Thanks for your useful reply! I have solved this problem. 













At 2024-08-31 23:04:53, "Rawal Khirodkar" ***@***.***> wrote:

Hello, looks like the pretrain module is not correctly installed.

Did you try cd $SAPIENS_ROOT/pretrain; pip install -e . ?

If yes, please uninstall the current mmpretrain packge - this might be conflict.

**Comment by womuer** [comment]
I used cd $SAPIENS_ROOT/pretrain; pip install -e .     but problem still exist. Is something I missing. My mmpretrain version is 1.2.0. and I don't find mmpretrain requirements dependcy in pretrain files.

**Comment by dhingratul** [comment]
Does anyone have a solve for this ?
