### ISSUE TITLE
Can the 3D model be exported？

### ISSUE THREAD

**Issue by ediiiwang** [facebookresearch/sapiens#47]
Is it possible to package the 3D model like PIfuHD or ECON and then export it as a standard OBJ or STL format file? If so, how should I proceed? Thank you.

**Comment by rawalkhirodkar** [comment]
@ediiiwang the model outputs are not 3d yet like pifuhd or econ. Therefore an export is not possible.

**Comment by ediiiwang** [comment]
If I want to output a 3D model similar to pifuhd or econ, what additional jobs do I need to take? Thanks
