### ISSUE TITLE
AssertionError: Please install mmdet to run the demo.

### ISSUE THREAD

**Issue by BrunoVDM** [facebookresearch/sapiens#49]
Hello, I followed all the step to install sapiens lite and perform inference.
However, I get the following message: "AssertionError: Please install mmdet to run the demo."
Can sombeboy help me, please?
Thank you in advance

**Comment by rawalkhirodkar** [comment]
Hello @BrunoVDM,
As mentioned in the [readme](https://github.com/facebookresearch/sapiens/blob/main/lite/docs/POSE_README.md).
- You can either not using a bounding box detector, simply remove the ```--det-config``` and ```--det-checkpoint``` from the python command.
- Or you can install mmdet following:
```
export SAPIENS_ROOT=/path/to/sapiens
cd $SAPIENS_ROOT/engine; pip install -e .
cd $SAPIENS_ROOT/cv; pip install -e .
cd $SAPIENS_ROOT/det; pip install -e .
```
