### ISSUE TITLE
how to use image encoder result to do skin segmentation?

### ISSUE THREAD

**Issue by thesby** [facebookresearch/sapiens#51]
The output of image encoder is a 1536*64*64 feature, how to convert it to an image mask with 2 channels ?

**Comment by rawalkhirodkar** [comment]
Hello, the image feature dimensions are C x H x W, i.e 1536 x 64 x 64 for 1B model at 1024 x 1024 image resolution. 

To convert this into skin segmentation, you will have to finetune the network on your data. Finetuning guideline for segmentation are coming soon.

Alternatively, you can use the existing segmentation models and their class labels to reason about skin.
