### ISSUE TITLE
get human body keypoints only when use the '308'  model

### ISSUE THREAD

**Issue by luoshuiyue** [facebookresearch/sapiens#53]
hello~ there are points stored in a json file (run pose estimation),  May I ask how to acquire only the 17 human body key points when use the '308 keypoints' model?

**Comment by luoshuiyue** [comment]
and how do I use lines to connect key points, as in the example you provided (the second picture):
![1746ce7c77a5d27e994da214a4559e6](https://github.com/user-attachments/assets/796b2464-a33c-4010-b74f-b793f9ed8821)
![67f9f092da77eaa82b7e3d76a94da31](https://github.com/user-attachments/assets/66d94ebc-ca08-412f-8acb-d5a1d596778e)

**Comment by luoshuiyue** [comment]
when I follow full installation, I encounter this error:
![1725356424557](https://github.com/user-attachments/assets/624ca18a-fbed-489a-b14a-e649d484b4d0)

**Comment by rawalkhirodkar** [comment]
@luoshuiyue for the numpy error with xtcocotools, you will need to modify the xtcocotools slightly to be compatible with new numpy or alternatively downgrade numpy version.

More details here: https://github.com/open-mmlab/mmpose/issues/1939

**Comment by luoshuiyue** [comment]
> @luoshuiyue for the numpy error with xtcocotools, you will need to modify the xtcocotools slightly to be compatible with new numpy or alternatively downgrade numpy version.
> 
> More details [here](https://github.com/open-mmlab/mmpose/issues/1939).

I downgrade numpy version to 1.26.4, this error was gone but a new one appears:
![微信图片_20240905113944](https://github.com/user-attachments/assets/9eb6c8db-7d0c-4882-978e-802dc21fe918)

**Comment by rawalkhirodkar** [comment]
@luoshuiyue Thanks for sharing the log, in hindsight, downgrading numpy is not a good idea.

Following the link I shared, can you try ```pip install git+https://github.com/jin-s13/xtcocoapi```?
Let me know who it goes.
