### ISSUE TITLE
Is there a way to use this in Comfy?

### ISSUE THREAD

**Issue by VicThor-wpp** [facebookresearch/sapiens#56]
The Pose prediction looks pretty solid for a controlnet, is there a workflow or maybe someone build something to run this on ComfyUI?

**Comment by rawalkhirodkar** [comment]
Hello, we provide controlnet compatible images from the pose predictions, read more about this [here](https://github.com/facebookresearch/sapiens/blob/main/docs/POSE_README.md).
The related models weights for keypoints133 and keypoints17 will be released soon.
