### ISSUE TITLE
Evaluation of surface normal in THuman Dataset

### ISSUE THREAD

**Issue by tijiang13** [facebookresearch/sapiens#57]
Hello,

Thanks for the great work! Could you share a bit of more details on how the surface normals evaluated in THuman 2.0? I read your reply in other issues and it looks that the cosine similarity between normals in camera coordinate system is measured. 

But how were the cameras sampled? I guess the distance between the camera and object can play a huge factor here (c.f. weak perspective camera) especially as Sapiens has no prior knowledge over the camera's intrinsics during the inference? 

Best, Tianjian

**Comment by rawalkhirodkar** [comment]
Hello @tijiang13 ,
Please refer to Table. 6 of the paper for the normal evaluation metrics. We compute angular error and % within t deg.
<img width="717" alt="image" src="https://github.com/user-attachments/assets/896df6c4-a84f-48a8-9c61-ae4d783de280">

Cameras were randomly sampled between a fixed distance range - same set of images were used to evaluate all the methods. A perspective camera was used to generate the images from the THuman2.0 dataset.

**Comment by tijiang13** [comment]
Thanks, but I am wondering what the exact hyper parameter e.g. for the distribution of camera-object distance/focal length -- I might also need to evaluate my own method under a similar setting.

Best, Tianjian

**Comment by tijiang13** [comment]
Hi @rawalkhirodkar,

Just to add some additional context -- here is my current setting:

```Python
@dataclass
class RandomCameraConfig:
    """configuration for random camera pose generation
    note:
    1. azimuth and elevation are in degrees, camera_distance is in meters
    2. the object is centered at the origin
    3. the camera is looking at the origin
    """

    # image resolution
    height: int = 512
    width: int = 512

    # camera parameters (in degrees)
    azimuth_range: tuple[float, float] = (-180, 180)
    elevation_range: tuple[float, float] = (-10, 10)
    camera_distance_range: tuple[float, float] = (2.0, 3.0)

    # field of view
    fov_range: tuple[float, float] = (30, 60)
```

**Comment by tijiang13** [comment]
Thanks a lot!  -- Best, Tianjian
