### ISSUE TITLE
pose_keypoints308.sh: line 90: 18134 Bus error               CUDA_VISIBLE_DEVICES=${VALID_GPU_IDS[GPU_ID]} pytho n ${RUN_FILE} ${CHECKPOINT} --num_keypoints 308 --det-config ${DETECTION_CONFIG_FILE} --det-checkpoint ${DETECTI ON_CHECKPOINT} --batch-size ${BATCH_SIZE} --input "${INPUT}/image_paths_$((i+1)).txt" --output-root="${OUTPUT}" --radius ${RADIUS} --kpt-thr ${KPT_THRES}

### ISSUE THREAD

**Issue by kafei123456** [facebookresearch/sapiens#58]
I can.t locate what happen? This is error showing.
Distributing 100 image paths into 1 jobs.
/usr/local/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/mmengine/optim/optimizer/zero_optimizer.py:1
1: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a fu
ture PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Loads checkpoint by local backend from path: /usr/share/docker/sapiens/sapiens_lite_host/torchscript/detector/ch
eckpoints/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth
/usr/local/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/mmengine/runner/checkpoint.py:317: FutureWar
ning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default p
ickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code dur
ing unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details).
 In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions
that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode
 unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you
 start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please
 open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, map_location=map_location)
  0%|                                                                                    | 0/25 [00:00<?, ?it/s]
/usr/local/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/mmdet/models/layers/se_layer.py:158: FutureW
arning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` inste
ad.
  with torch.cuda.amp.autocast(enabled=False):
/usr/local/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/mmdet/models/backbones/csp_darknet.py:118: F
utureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)`
 instead.
  with torch.cuda.amp.autocast(enabled=False):
  4%|███                                                                         | 1/25 [00:25<10:11, 25.48s/it]
pose_keypoints308.sh: line 90: 18134 Bus error               CUDA_VISIBLE_DEVICES=${VALID_GPU_IDS[GPU_ID]} pytho
n ${RUN_FILE} ${CHECKPOINT} --num_keypoints 308 --det-config ${DETECTION_CONFIG_FILE} --det-checkpoint ${DETECTI
ON_CHECKPOINT} --batch-size ${BATCH_SIZE} --input "${INPUT}/image_paths_$((i+1)).txt" --output-root="${OUTPUT}"
--radius ${RADIUS} --kpt-thr ${KPT_THRES}
/usr/share/docker/sapiens/lite/scripts/demo/torchscript

**Comment by rawalkhirodkar** [comment]
Hello @kafei123456 ,

I see an bus error. This is likely related to cuda/gpu issue and not related to sapiens. 
Can you ensure if there is not mismatch between cuda and gpu driver? Another test would be if you can run torch functions with cuda enabled.
