### ISSUE TITLE
Hugging Face Depth Estimation, appears to be not working correctly

### ISSUE THREAD

**Issue by jones873** [facebookresearch/sapiens#59]
Hi I`ve tryed the demo on various uploaded pictures and all I am getting on all of them is black patches, it seems to work fine on all the example photos. Is there something i`m missing please? many thanks

![Wedding Picture Color](https://github.com/user-attachments/assets/2eedc14d-7a15-4674-bce7-f3781bd73806)

![image-1](https://github.com/user-attachments/assets/16ea5a96-a942-407d-bd3a-25c1e721aeaf)

**Comment by NinoNeumann** [comment]
I've encountered a similar issue. I hope the author can provide a model with better weight parameters or offer a detailed explanation of why the performance of the pre-trained model is so poor.
