### ISSUE TITLE
when do keypoints17 and keypoints133 models become available

### ISSUE THREAD

**Issue by bowieshi** [facebookresearch/sapiens#60]
Thanks for your excellent work!!! Can I ask when do keypoints17 and keypoints133 models become available. And Can I ask whether the keypoints17 and keypoints133 models will be faster than keypoints308 in inference time?

**Comment by APeiZou** [comment]
https://github.com/facebookresearch/sapiens/issues/60#issue-2505324645   我在做17点的demo的时候也出现了the length of kpt_color (17) does not matches that of keypoints (308)

**Comment by xdfeng07** [comment]
> Thanks for your excellent work!!! Can I ask when do keypoints17 and keypoints133 models become available. And Can I ask whether the keypoints17 and keypoints133 models will be faster than keypoints308 in inference time?

you can only process the heatmaps corresponding to the 17 or 133 kps, this will greatly cut down the heatmap proc time from over 200ms to only about 30ms, while the evaluation of model costs about 800ms, this would be quite a boost to the speed

**Comment by rawalkhirodkar** [comment]
@bowieshi https://huggingface.co/noahcao/sapiens-pose-coco
