### ISSUE TITLE
Depth Estimation

### ISSUE THREAD

**Issue by juntaosun** [facebookresearch/sapiens#61]
Thanks for this wonderful project!

Depth estimation uses a mask to remove the background by default. Can it support retaining the depth background? 

![test](https://github.com/user-attachments/assets/fe5c7eab-f6a6-41d9-83aa-92832b92f140)

How to do it without removing depth background?

**Comment by rawalkhirodkar** [comment]
@juntaosun sapiens are only supervised on human depth. We do not provide support for background depth reasoning as of now.
