### ISSUE TITLE
different size of tensor

### ISSUE THREAD

**Issue by sebastianopazo1** [facebookresearch/sapiens#63]
Hi, I'm having some issues trying to run de lite version for segmentation on my own images. I have the following error:
 0%|                                                                                                                                                                           | 0/57 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/seba/Documents/sapiens/lite/demo/vis_seg.py", line 272, in <module>
    main()
  File "/home/seba/Documents/sapiens/lite/demo/vis_seg.py", line 242, in main
    result = inference_model(exp_model, batch_imgs, dtype=dtype)
  File "/home/seba/Documents/sapiens/lite/demo/vis_seg.py", line 58, in inference_model
    results = model(imgs.to(dtype).cuda())
  File "/home/seba/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/seba/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/mmpretrain/models/selfsup/mae.py", line 13, in forward
    inputs: Tensor) -> Tuple[Tensor]:
    backbone = self.backbone
    return ((backbone).forward(inputs, ),)
             ~~~~~~~~~~~~~~~~~ <--- HERE
class MAEViT(Module):
  __parameters__ = ["cls_token", "pos_embed", ]
  File "code/__torch__/mmpretrain/models/selfsup/mae.py", line 87, in forward
    cls_token0 = torch.expand(cls_token, [_24, -1, -1])
    x = torch.cat([cls_token0, _25], 1)
    input = torch.add(x, pos_embed)
            ~~~~~~~~~ <--- HERE
    _30 = (drop_after_pos).forward(input, )
    _31 = (pre_norm).forward()

Traceback of TorchScript, original code (most recent call last):
/home/rawalk/Desktop/sapiens/pretrain/mmpretrain/models/backbones/vision_transformer.py(553): forward
/home/rawalk/Desktop/sapiens/pretrain/mmpretrain/models/selfsup/mae.py(176): forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1522): _slow_forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
/home/rawalk/Desktop/sapiens/pretrain/mmpretrain/models/selfsup/mae.py(334): extract_feat
/home/rawalk/Desktop/sapiens/pretrain/mmpretrain/models/selfsup/mae.py(326): forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1522): _slow_forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/jit/_trace.py(1088): trace_module
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/jit/_trace.py(820): trace
/home/rawalk/Desktop/sapiens/pretrain/tools/deployment/pytorch2torchscript.py(46): pytorch2libtorch
/home/rawalk/Desktop/sapiens/pretrain/tools/deployment/pytorch2torchscript.py(100): <module>
RuntimeError: The size of tensor a (3073) must match the size of tensor b (4097) at non-singleton dimension 1

/home/seba/Documents/sapiens/lite/scripts/demo/torchscript
Processing complete.
Results saved to ./assets/output/sapiens_0.3b

I'm using images of 1024x768, so that shouldn't be the problem.
Thanks for your help!

**Comment by rawalkhirodkar** [comment]
@sebastianopazo1 looks like you are not using the segmentation checkpoint, the log says pretrain checkpoint is being called.

Can you tell me the checkpoint you are using?
PS: you don't need to resize the images explictly, our loaders do it automatically during inference.

**Comment by starlightlmy** [comment]
I used the checkpoints downloaded from [CHECKPOINT=$SAPIENS_CHECKPOINT_ROOT/pretrain/checkpoints/sapiens_1b/sapiens_1b_epoch_173_$MODE.pt2](https://huggingface.co/facebook/sapiens/tree/main/sapiens_lite_host/torchscript/pretrain/checkpoints/sapiens_1b), why still met the same problem??? Thanks for your help!!!


Distributing 100 image paths into 1 jobs.
  0%|                                                                  | 0/100 [00:00<?, ?it/s]
  0%|                                                                  | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/liumengyin/human/sapiens/lite/demo/extract_feature.py", line 227, in <module>
    main()
  File "/data/liumengyin/human/sapiens/lite/demo/extract_feature.py", line 207, in main
    results = inference_model(model, batch_imgs, dtype=dtype)   ### 报错
  File "/data/liumengyin/human/sapiens/lite/demo/extract_feature.py", line 60, in inference_model
    (results,) = model(imgs.to(dtype).cuda())
  File "/data/liumengyin/.conda/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/liumengyin/.conda/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/mmpretrain/models/selfsup/mae.py", line 13, in forward
    inputs: Tensor) -> Tuple[Tensor]:
    backbone = self.backbone
    return ((backbone).forward(inputs, ),)
             ~~~~~~~~~~~~~~~~~ <--- HERE
class MAEViT(Module):
  __parameters__ = ["cls_token", "pos_embed", ]
  File "code/__torch__/mmpretrain/models/selfsup/mae.py", line 135, in forward
    cls_token0 = torch.expand(cls_token, [_48, -1, -1])
    x = torch.cat([cls_token0, _49], 1)
    input = torch.add(x, pos_embed)
            ~~~~~~~~~ <--- HERE
    _54 = (drop_after_pos).forward(input, )
    _55 = (pre_norm).forward()

Traceback of TorchScript, original code (most recent call last):
/home/rawalk/Desktop/sapiens/pretrain/mmpretrain/models/backbones/vision_transformer.py(553): forward
/home/rawalk/Desktop/sapiens/pretrain/mmpretrain/models/selfsup/mae.py(176): forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1522): _slow_forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
/home/rawalk/Desktop/sapiens/pretrain/mmpretrain/models/selfsup/mae.py(334): extract_feat
/home/rawalk/Desktop/sapiens/pretrain/mmpretrain/models/selfsup/mae.py(326): forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1522): _slow_forward
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/jit/_trace.py(1088): trace_module
/uca/conda-envs/dgxenv-2024-07-25-10-44-26-x6252-centos9-py310-pt231/lib/python3.10/site-packages/torch/jit/_trace.py(820): trace
/home/rawalk/Desktop/sapiens/pretrain/tools/deployment/pytorch2torchscript.py(46): pytorch2libtorch
/home/rawalk/Desktop/sapiens/pretrain/tools/deployment/pytorch2torchscript.py(100): <module>
RuntimeError: The size of tensor a (197) must match the size of tensor b (4097) at non-singleton dimension 1

/data/liumengyin/human/sapiens/lite/scripts/demo/torchscript
Processing complete.
Results saved to /data/liumengyin/human/sapiens/lite/output_forder/pretrain/sapiens_2b
