### ISSUE TITLE
Huggin Face Depthmap Demo, please consider pulling this until users are able to get consistent depthmaps

### ISSUE THREAD

**Issue by jones873** [facebookresearch/sapiens#64]
Tried again with the new update, the same problem occurs, and on the bas-relief image nothing was produced.
I cannot believe a company as big as Meta would allow something  as bad a this to be put out in the public domain....

![Untitled](https://github.com/user-attachments/assets/49bda95b-a159-4794-a291-7ee005c44bbc)
![Untitled 2](https://github.com/user-attachments/assets/76699f3d-f0f0-4e82-997c-12b8d1a37333)

**Comment by rawalkhirodkar** [comment]
@jones873 This is a failure of the foreground segmentation model - the images you shared are out of distribution of our segmentation labels. To resolve this, we have added a "no-bg-removal" option to Background Removal Model. 
This will visualize the depth prediction for the entire image. Results on your images below:

<img width="1128" alt="image" src="https://github.com/user-attachments/assets/ba6398e3-2904-49f0-92a3-c343ba686520">
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/633fc988-59fe-45a4-b767-916b0c7890d4">

**Comment by GloryyrolG** [comment]
> @jones873 This is a failure of the foreground segmentation model - the images you shared are out of distribution of our segmentation labels.
> 
> To resolve this, we have added a "no-bg-removal" option to Background Removal Model. This will visualize the depth/normal prediction for the entire image. Note, our models are supervised only on human pixels.
> 
> Results on your images below: <img alt="image" width="1128" src="https://private-user-images.githubusercontent.com/8392905/364890234-ba6398e3-2904-49f0-92a3-c343ba686520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDY4MTcsIm5iZiI6MTcyODMwNjUxNywicGF0aCI6Ii84MzkyOTA1LzM2NDg5MDIzNC1iYTYzOThlMy0yOTA0LTQ5ZjAtOTJhMy1jMzQzYmE2ODY1MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDdUMTMwODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmM1MzYzYzJkYzUyNmFlZWZlNTRkNzAzYmZiYTFjYmQ2MGE1MTg4ZGM1MDQwZGI1OTAzZGQ2NWIyZjUyN2ViOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gO3p4a6LtnraGR-1WHlv4p2aMxTHnN-ZD3nCmLQa0O0"> <img alt="image" width="1125" src="https://private-user-images.githubusercontent.com/8392905/364890463-633fc988-59fe-45a4-b767-916b0c7890d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDY4MTcsIm5iZiI6MTcyODMwNjUxNywicGF0aCI6Ii84MzkyOTA1LzM2NDg5MDQ2My02MzNmYzk4OC01OWZlLTQ1YTQtYjc2Ny05MTZiMGM3ODkwZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDdUMTMwODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWMwNDU1OTNiMzkyYzU4OThjZjQwNDMxYzcwNmMyNjBkNWJjMWY0OGRhNWZjYWU2MDMxMmNjMTEyZTg4MDFlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._0CSjP_D7zwKu3EeZ0E_92UaMOFg0BNNOFqNKrV1Eps">
> 
> <img alt="image" width="1122" src="https://private-user-images.githubusercontent.com/8392905/364892079-7025fe27-1d7e-41c3-b2ca-d891e381d239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDY4MTcsIm5iZiI6MTcyODMwNjUxNywicGF0aCI6Ii84MzkyOTA1LzM2NDg5MjA3OS03MDI1ZmUyNy0xZDdlLTQxYzMtYjJjYS1kODkxZTM4MWQyMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDdUMTMwODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjUwYjM2MzBmNzVlOGI4OGU0ZGI5MDRhMDQyMTExMWI4YzY5OGE0MTU4NjZlMmUxZDFlZGMxOTBiYTRkZjBkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ppk3kz2k1GhufkGLj3kn0RujOML6w7UlrbTzh-__0Fo"> <img alt="image" width="1115" src="https://private-user-images.githubusercontent.com/8392905/364891775-10f610ec-1541-47e6-b0e5-aed42dfc28b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDY4MTcsIm5iZiI6MTcyODMwNjUxNywicGF0aCI6Ii84MzkyOTA1LzM2NDg5MTc3NS0xMGY2MTBlYy0xNTQxLTQ3ZTYtYjBlNS1hZWQ0MmRmYzI4YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDdUMTMwODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzFhZmNjNTUxZDQ3ODBlMzg3ZGY3M2M1ODU4NDExYWEyZjgzODNiMmFhNTFlMjUzOWFiMmE3NzRkNDJhOTAzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xjhdLDXPZ5GVDaiH7LYkyNo8AI7p7wkZK2cz1f_0dys">

hi @rawalkhirodkar then may i ask why not to use a person detector like detectron2/yolox to replace sensitive segmentation?
