### ISSUE TITLE
Metric depth + temporal consistency?

### ISSUE THREAD

**Issue by Luke2642** [facebookresearch/sapiens#67]
Do you have any plans to have a metric depth output?

I realise without camera fov information accuracy might not be high?

Maybe for improved temporal consistency it could use 'zero' as the depth to centre of mass, or an optimal point, the front of the L3 vertibrae something? Then plus/minus from there?

**Comment by rawalkhirodkar** [comment]
Hi @Luke2642, yes, we did attempt metric depth - as you said, without camera intrinsics, the results are not reliable.
This direction is still under exploration. 

To anchor the predicted relative depth from Sapiens, you can use other metric estimators like [ZoeDepth](https://github.com/isl-org/ZoeDepth) or [iPhone depth sensing, an example with sapiens](https://rawalkhirodkar.github.io/sapiens/static/videos/iphone_vs_sapiens.mp4).
