### ISSUE TITLE
pose estimation demo code not giving expected output.

### ISSUE THREAD

**Issue by arun477** [facebookresearch/sapiens#7]
Hey, nice work!

I'm trying to run the model in the notebook, but the results seem a little off.
I've attached my test Colab run notebook below. I’m probably doing something wrong.

[colab_test_run](https://colab.research.google.com/drive/14cu0pqa88X_Z-AGUnXxJ0FfXj_Y2VJCD?usp=sharing)

Thanks!

output for the pose estimation:
![image](https://github.com/user-attachments/assets/e68afea4-225a-4e42-98e2-7d1cb7a12b92)

**Comment by rawalkhirodkar** [comment]
Hello, you are using an incorrect (pretrained) checkpoint for pose estimation. 

Please use the finetuned 308 keypoints checkpoint (also change the dataset from coco_wholebody to goliath).

**Comment by arun477** [comment]
@rawalkhirodkar, thanks! It works now.

for anyone's reference  [sample working test run colab notebook](https://colab.research.google.com/drive/10D96zjTMSz-0-f3n5dWH9Kn3CeBqFkJS?usp=sharing)

![image](https://github.com/user-attachments/assets/853db538-79b8-47c5-9b27-7ff84bf23bdb)
