### ISSUE TITLE
bfloat16 checkpoint release date?

### ISSUE THREAD

**Issue by christiankotait** [facebookresearch/sapiens#70]

**Comment by rawalkhirodkar** [comment]
@christiankotait they are released now: https://huggingface.co/collections/facebook/sapiens-66d22047daa6402d565cb2fc

**Comment by christiankotait** [comment]
@zyhbili I downgraded for pytorch==2.4 to pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=12.1, and I no longer have this problem.

**Comment by zyhbili** [comment]
> @zyhbili I downgraded from pytorch==2.4 to pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=12.1, and I no longer have this problem.

Solved! Thank you very much!
