### ISSUE TITLE
AssertionError: Arch sapiens_1b is not in default archs {'deit-tiny', 'eva-g', 'deit-t', 'large', 'eva-giant', 'deit-small', 'dinov2-giant', 'b', 'h', 'base', 'huge', 'dinov2-g', 'dinov2-small', 'deit-s', 'small', 'dinov2-s', 's', 'deit-base', 'deit-b', 'l'}

### ISSUE THREAD

**Issue by LW-CVer** [facebookresearch/sapiens#71]

**Comment by Ky1eYang** [comment]
use pretrain/mmpretrain as the package mmpretrain, or you can find the arch dict in pretrain/mmpretrain/models/backbones/vision_transformer. 
the arch setting of sapiens_1b is {
                'embed_dims': 1536,
                'num_layers': 40,
                'num_heads': 24,
                'feedforward_channels': 1536 * 4
            }
you can also replace the model_name to arch setting in config.py

**Comment by winner-4** [comment]
Hello, have you solved this problem now? I have also encountered the same problem.

**Comment by favorxin** [comment]
> Hello, please uninstall existing mmpretain and install the modified pretrain module provided in the repo from source.

Sorry! I can not find the modified pretrain module in the repo. Could you post the place of the module? Thanks.

**Comment by favorxin** [comment]
> Hello, have you solved this problem now? I have also encountered the same problem.

here is the way to solve the problem https://github.com/facebookresearch/sapiens/issues/46#issuecomment-2322926087
