### ISSUE TITLE
Sapiens-Lite 2B Body Part Segmentation Failed on clothing

### ISSUE THREAD

**Issue by matabear-wyx** [facebookresearch/sapiens#8]
Hi, I'm performing Body Part Segmentation inference using sapiens_2b_goliath_best_goliath_mIoU_8179_epoch_181_torchscript.pt2, and I got results like these:

![00947](https://github.com/user-attachments/assets/4031181e-f454-4130-a17e-26a69c865326)
![01529](https://github.com/user-attachments/assets/509891f6-340c-4dd0-b86b-7de881c3279a)

I even modified the visualization threshold from 0.3 to 0

**Comment by chopin1998** [comment]
i've encountered the same issue, there are holes in both seg and depth...

**Comment by chopin1998** [comment]
> @chopin1998 this should not be an issue with depth estimation, can you share your depth results?

could check those video file?

https://office.tensor-robotics.com:5555/~marco/e79b3e9d86d9c32735a4f3695cb0500c.mp4

https://office.tensor-robotics.com:5555/~marco/ed7cfc4c98d9d95968d6abd9c141e9b7.mp4

**Comment by rawalkhirodkar** [comment]
@chopin1998 for relative depth visualization, we re-scale the depth prediction in [0, 1] using foreground vs background segmentation, [refer] (https://github.com/facebookresearch/sapiens/blob/4bcff2bdf26f7f9f506722ac147909db960e019c/lite/demo/vis_depth.py#L110).

Main cause: segmentation. If you have the fb/bg masks, you can use them in the depth visualization.
