### ISSUE TITLE
why I get black normal map?

### ISSUE THREAD

**Issue by Dan1900** [facebookresearch/sapiens#80]
I tested several images,and I get some error normal maps.
![000](https://github.com/user-attachments/assets/75c968ce-d1b8-442e-b0dd-22b7921c5ba8)
![009](https://github.com/user-attachments/assets/06b70fd1-3906-4668-8b8e-5fe8fa513dc8)

**Comment by rawalkhirodkar** [comment]
@Dan1900 can you try normal demo space with these images first? This is a segmentation model failure on your images with black background. 

You can control the background removal method and check what works best for you. Start with no-bg-removal. 

https://huggingface.co/spaces/facebook/sapiens-normal

**Comment by Dan1900** [comment]
> @Dan1900 can you try normal demo space with these images first? This is a segmentation model failure on your images with black background.
> 
> You can control the background removal method and check what works best for you. Start with no-bg-removal.
> 
> https://huggingface.co/spaces/facebook/sapiens-normal

Thank you!I'll try it.
