### ISSUE TITLE
Demo for video

### ISSUE THREAD

**Issue by sophielach** [facebookresearch/sapiens#82]
Would you consider adding the ability to upload short videos to the demo?  Thanks so much.

**Comment by rawalkhirodkar** [comment]
@sophielach there are no plans of supporting video demos as of now.
Please check out other demos by the community which support video inference. https://huggingface.co/spaces/joselobenitezg/sapiens-demo

**Comment by YangJae96** [comment]
@rawalkhirodkar  Hi, when I tried your link, upload a image and run, a error occurs like below
![image](https://github.com/user-attachments/assets/99d7e1e3-37b6-4793-aef0-3e2a9ae3fb6d)

How should I solve this problem?!

Thanks in advance.
