### ISSUE TITLE
Fine tuning depth estimation BUG

### ISSUE THREAD

**Issue by whitelin0321** [facebookresearch/sapiens#83]
have no $SAPIENS_ROOT/seg/scripts/finetune/depth_general/sapiens_1b/node.sh
and DepthGeneralDataset is not in the mmseg::dataset registry.   

first:
copy $SAPIENS_ROOT/seg/scripts/finetune/normal_general/sapiens_1b/node.sh to $SAPIENS_ROOT/seg/scripts/finetune/depth_general/sapiens_1b/node.sh

second:
add  
from .depth_general import DepthGeneralDataset
__all__ = [.....,'DepthGeneralDataset']
to
$SAPIENS_ROOT/sapiens/seg/mmseg/datasets/__init__.py

**Comment by rawalkhirodkar** [comment]
@whitelin0321 thank for pointing this out. Resolved.
