### ISSUE TITLE
How to test on coco-wholebody with mmpose

### ISSUE THREAD

**Issue by zxk19981227** [facebookresearch/sapiens#84]
I have tried several ways to test the sapines result. However, when i use this method and the result becomes extremely strange.
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.161
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.204
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.177
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.218
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.158
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.691
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.846
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.748
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.593
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.823

I tried to test with official mmpose, but the error is 
AssertionError: Arch sapiens_1b is not in default archs {'deit-s', 'eva-g', 'small', 'base', 'eva-giant', 'deit-tiny', 'deit-small', 'b', 'deit-t', 'deit-base', 'dinov2-giant', 'huge', 'dinov2-s', 'large', 'l', 's', 'h', 'dinov2-small', 'deit-b', 'dinov2-g'}

How can I solve This?

**Comment by rawalkhirodkar** [comment]
@zxk19981227 you can evaluate using the pose module. In the coming days, we will be adding support for evaluation on COCO (17 and 133 kps). To unblock you for now, please use this:

```
cd ../../../..

###--------------------------------------------------------------
# DEVICES=0,
DEVICES=0,1,2,3,4,5,6,7,

RUN_FILE='./tools/dist_test.sh'
PORT=$(( ((RANDOM<<15)|RANDOM) % 63001 + 2000 ))

##---------copy this to the slurm script-----------------
####-----------------MODEL_CARD----------------------------
DATASET='coco_wholebody'
MODEL="sapiens_2b-210e_${DATASET}-1024x768"
JOB_NAME="test_pose_whole_$MODEL"
TEST_BATCH_SIZE_PER_GPU=32

CHECKPOINT='/home/sapiens_host/pose/checkpoints/sapiens_2b/sapiens_2b_coco_wholebody_best_coco_wholebody_AP_745.pth'

##--------------------------------------------------------------
# ## val set
EVAL_SET='val2017'; DETECTION_AP=70 ## best for val


#---------------------------------------------------------------
# mode='debug'
mode='multi-gpu'

###--------------------------------------------------------------+
BBOX_FILE=data/coco/person_detection_results/COCO_${EVAL_SET}_detections_AP_H_${DETECTION_AP}_person.json
CONFIG_FILE=configs/sapiens_pose/${DATASET}/${MODEL}.py
OUTPUT_DIR="Outputs/test/${DATASET}/${MODEL}/node"
OUTPUT_DIR="$(echo "${OUTPUT_DIR}/$(date +"%m-%d-%Y_%H:%M:%S")")"

###--------------------------------------------------------------
if [ "$EVAL_SET" = "val2017" ]; then
    ANNOTATION_FILE=annotations/coco_wholebody_val_v1.0.json
    IMG_PREFIX=${EVAL_SET}/

else
    ANNOTATION_FILE=annotations/image_info_test-dev2017.json
    IMG_PREFIX=test2017/
fi

export TF_CPP_MIN_LOG_LEVEL=2

## set the options for the test
OPTIONS="$(echo "test_dataloader.batch_size=$TEST_BATCH_SIZE_PER_GPU
    test_dataloader.dataset.bbox_file=${BBOX_FILE}
    test_dataloader.dataset.ann_file=$ANNOTATION_FILE
    test_dataloader.dataset.data_prefix.img=${IMG_PREFIX}
    test_evaluator.ann_file=data/coco/$ANNOTATION_FILE
    ")"

##--------------------------------------------------------------
## if mode is multi-gpu, then run the following
## else run the debugging on a single gpu
if [ "$mode" = "debug" ]; then
    TEST_BATCH_SIZE_PER_GPU=16 ## works for single gpu

    OPTIONS="$(echo "test_dataloader.batch_size=${TEST_BATCH_SIZE_PER_GPU} test_dataloader.num_workers=0 test_dataloader.persistent_workers=False")"
    CUDA_VISIBLE_DEVICES=${DEVICES} python tools/test.py ${CONFIG_FILE} ${CHECKPOINT} --work-dir ${OUTPUT_DIR} --cfg-options ${OPTIONS}

elif [ "$mode" = "multi-gpu" ]; then
    NUM_GPUS_STRING_LEN=${#DEVICES}
    NUM_GPUS=$((NUM_GPUS_STRING_LEN/2))

    LOG_FILE="$(echo "${OUTPUT_DIR}/log.txt")"
    mkdir -p ${OUTPUT_DIR}; touch ${LOG_FILE}

    CUDA_VISIBLE_DEVICES=${DEVICES} PORT=${PORT} ${RUN_FILE} ${CONFIG_FILE} ${CHECKPOINT}\
            ${NUM_GPUS} \
            --work-dir ${OUTPUT_DIR} \
            --cfg-options ${OPTIONS} \
            | tee ${LOG_FILE}

fi
```

**Comment by rawalkhirodkar** [comment]
@wxhqw We have, the results worsen by about 1 mAP. This default setting is now 5 years old, its about time we move on. Feel free to choose detections as per your choice.

**Comment by zxk19981227** [comment]
> @wxhqw We have, the results worsen by about 1 mAP. This default setting is now 5 years old, its about time we move on. Feel free to choose detections as per your choice.

Could you release the whole results as the coco-wholebody does?

**Comment by rawalkhirodkar** [comment]
@zxk19981227 Sorry, this is not planned.
