### ISSUE TITLE
bfloat16 checkpoint failed to load

### ISSUE THREAD

**Issue by HarryWang355** [facebookresearch/sapiens#85]
Hi! When I tried to load sapiens-depth-1b-bfloat16 checkpoint for finetuning the depth estimation model, I encountered this error:
`[rank0]: RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted`
I was able to load the sapiens-depth-1b model just fine. Is this a problem with the checkpoint?

**Comment by rawalkhirodkar** [comment]
@HarryWang355 bfloat16 and torchscript checkpoints are only for inference.
For finetuning with full-install, please use the original (.pth) checkpoints.
