### ISSUE TITLE
Question: depth estimation finetuning resources required for the model

### ISSUE THREAD

**Issue by VillardX** [facebookresearch/sapiens#87]
Thank you for your amazing work. I am currently interested in finetuning the depth estimation model, but I would like to better understand the resources required to do so.

Could you please provide some information on the following:

Approximate GPU/TPU requirements

Estimated training time

Best regards,

Villard

**Comment by rawalkhirodkar** [comment]
@VillardX This depends on the backbone of your choice and number of training samples you have.

For sapiens-1b, we use around 16 A100 gpus to finetune for about 1 week. 

This setting will be lower for sapiens-0.3b
