### ISSUE TITLE
Compare Finetuning Surface Normal Estimation sapiens_1b and sapiens_2b

### ISSUE THREAD

**Issue by whitelin0321** [facebookresearch/sapiens#88]
One NVIDIA A800 80GB 
Finetuning Surface Normal Estimation sapiens_1b patch_size = 16
Finetuning Surface Normal Estimation sapiens_2b patch_size = 32 ,because CUDA out of memory for patch_size = 16
but two reaults very bad，As shown in the following figure
 What should I do ?  Looking forward to your response ,thank you ! 
andI have a question，Why do we use the corresponding configuration file in normal_general when fine-tuning, while the configuration file used in the demo is in normal_rended_people? Is there any difference between the two
![image](https://github.com/user-attachments/assets/c77ba0c5-f5d2-4e62-b333-83f8baa5888d)

**Comment by whitelin0321** [comment]
From the results, I'm not sure if the data used for fine-tuning is correct. Can you provide some sample data for fine-tuning ?

**Comment by rawalkhirodkar** [comment]
@whitelin0321 Hello,

What data are you using for finetuning? Is it the 50 samples from the toy set? This is not enough to train Sapiens.

Changing patch size for sapiens 2b from 16 to 32: This is probably not a good idea as you are moving away from the pretraining configuration. As a result, finetuning will require more compute and data to compensate. 

Difference between demo config and finetuning config: Both configuration are exactly the same except the dataset used for loading.

**Comment by whitelin0321** [comment]
hi, rawalkhircodkar 
We use our own human body datas

**Comment by rawalkhirodkar** [comment]
@whitelin0321 In that case, I would recommend completing the finetuning for the entire training schedule. 

We use aggressive learning rates at the beginning, which can result in poor results if you stop too early. The other factor to consider is also the quality of annotations.

**Comment by whitelin0321** [comment]
thank you!  I'll give it a try . How can I confirm if the human body data I use for fine-tuning meets the requirements

**Comment by rawalkhirodkar** [comment]
Qualitative comparison of the normals shared in the toy dataset vs your data would be a good starting point.

**Comment by whitelin0321** [comment]
I have a dataset of human body photos and I would like to know the process of creating normal image data. Is it using tangent space, object space, or something else
