### ISSUE TITLE
How to make sapiens compatible with mmpose

### ISSUE THREAD

**Issue by ds22058** [facebookresearch/sapiens#89]
Hi, thank you for your great work!
I have two questions:
1. I am interested in pose estimation part and successfully inference in both lite and full version. However, the two results are different. Is it noraml?
2. I try to run inference under the environment of [https://github.com/open-mmlab/mmpose](url), but an error occurred：
`'mmpretrain.VisionTransformer is not in the mmpose::model registry. Please check whether the value of mmpretrain.VisionTransformer is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'`.
So I run `pip install -e . -v` under pretrain and then inference can run successfully, but the result seems abnormal. I guess maybe it is caused by the diference between the installation of mmpose, mmdet and mmcv. 
I am wondering how can I make sapiens compatible with mmpose. Can you help me?

**Comment by rawalkhirodkar** [comment]
1. There might be a slight difference in results due to porting the models to other formats like torchscript/bfloat16.

2. The pose module is infact a forked mmpose lib. I would recommend use this module as it has changes compatible with our models.

**Comment by rawalkhirodkar** [comment]
@ds22058 Support to evaluate models on coco and coco-wholebody is now added.
Please refer to https://github.com/facebookresearch/sapiens/blob/main/docs/evaluate/POSE_README.md
