### ISSUE TITLE
Webcam mode?

### ISSUE THREAD

**Issue by joansc** [facebookresearch/sapiens#91]
Are there any plans to release a webcam mode different than the current image/video workflows?

**Comment by rawalkhirodkar** [comment]
@joansc sorry this is not planned.

**Comment by joansc** [comment]
So Sapiens is only meant to work offline and not in realtime cases?

**Comment by rawalkhirodkar** [comment]
@joansc sapiens-0.3b and sapiens-0.6b can run in realtime on a gpu.

**Comment by Gnoot01** [comment]
@rawalkhirodkar Hi, how do we activate webcam mode? For example in the pose/demo/demo_vis.py, this is specified but there is no actual opening of the webcam. Video mode also seems to not work with mp4, like we have to break it into images ourselves, correct? Thanks!

```
if args.output_root:
        mmengine.mkdir_or_exist(args.output_root)
        output_file = os.path.join(args.output_root,
                                   os.path.basename(args.input))
        if args.input == 'webcam':
            output_file += '.mp4'
```

**Comment by Gnoot01** [comment]
With regards to the webcam mode, what about for segmentation model as well?

**Comment by joansc** [comment]
I did a quick test emulating a webcam mode and got 17 FPS on the 0.3b model and 11 FPS on the 0.6b model for the 17 keypoints on a stream of 1024x768px. I'm using a desktop PC with a 4090 GPU, so I find it slow compared to other solutions like MediaPipe, and the results don't show any significant improvement in accuracy.

**Comment by Gnoot01** [comment]
> I did a quick test emulating a webcam mode and got 17 FPS on the 0.3b model and 11 FPS on the 0.6b model for the 17 keypoints on a stream of 1024x768px. I'm using a desktop PC with a 4090 GPU, so I find it slow compared to other solutions like MediaPipe, and the results don't show any significant improvement in accuracy.

Hi, how did you activate webcam mode? Is this for pose only also?

**Comment by rawalkhirodkar** [comment]
@Gnoot01 unfortunately the webcam mode is not supported. Pointer to implement this: [here](https://github.com/open-mmlab/mmpose/blob/5408bc76f5b848cf925a0d1857899011d8c5b497/demo/topdown_demo_with_mmdet.py#L222).

**Comment by Gnoot01** [comment]
@rawalkhirodkar does this mean sapiens at the moment is not fast enough or optimized for real-time inference yet? Thanks

**Comment by rawalkhirodkar** [comment]
@Gnoot01 The smaller models (0.3B, and 0.6B) are around 20 FPS depending on the task. You may want to checkout [sapiens on edge devices](https://github.com/facebookresearch/sapiens/issues/112).

**Comment by Gnoot01** [comment]
> @Gnoot01 The smaller models (0.3B, and 0.6B) are around 20 FPS depending on the task. You may want to checkout [sapiens on edge devices](https://github.com/facebookresearch/sapiens/issues/112).

Is this in lite mode (torchscript) only? or the full model as well?

**Comment by rawalkhirodkar** [comment]
@Gnoot01 lite models.
