### ISSUE TITLE
https://github.com/facebookresearch/sapiens/issues/90

### ISSUE THREAD

**Issue by Shaheerahmadzai** [facebookresearch/sapiens#93]
I appreciate your help, I‌ tried the same config and model checkpoint, but the problem still exists.

python3 demo/image_demo.py /home/sahmadzai/00_PROJECT/00_FULLBODY/SAPIENS_H_R_M_HUMAN_TASKS/sapiens/pose/INPUT/img.jpg /home/sahmadzai/00_PROJECT/00_FULLBODY/SAPIENS_H_R_M_HUMAN_TASKS/sapiens/pose/configs/sapiens_pose/coco_wholebody/sapiens_1b-210e_coco_wholebody-1024x768.py /home/sahmadzai/00_PROJECT/00_FULLBODY/SAPIENS_H_R_M_HUMAN_TASKS/sapiens/sapiens_host/pose/checkpoints/sapiens_1b/sapiens_1b_goliath_best_goliath_AP_640.pth?download=true --out-file /home/sahmadzai/00_PROJECT/00_FULLBODY/SAPIENS_H_R_M_HUMAN_TASKS/sapiens/pose/OUTPUT/new_pose_image.jpg

**Comment by rawalkhirodkar** [comment]
@Shaheerahmadzai again your config and model checkpoint do not match.

Config is for cocowholebody, checkpoint for goliath. Please use the provided shell scripts as reference to ensure consistency between config and checkpoint.
