### ISSUE TITLE
Face segmentation checkpoint

### ISSUE THREAD

**Issue by angusev** [facebookresearch/sapiens#94]
Hi, thank you for your great work! 🙌

I'm having trouble finding the HF face segmentation checkpoint that you mentioned here: https://github.com/facebookresearch/sapiens/blob/b45a199b9b6fe3488059241ab7c549077886510a/docs/SEG_README.md?plain=1#L100

Could you please point me to the correct HF link?

**Comment by rawalkhirodkar** [comment]
@angusev please checkout https://github.com/facebookresearch/sapiens/blob/main/docs/finetune/SEG_README.md to finetune for face segmentation. The release of the face segmentation checkpoint is not planned as of now.
