### ISSUE TITLE
finetune body part segmentation 

### ISSUE THREAD

**Issue by ShulingTang** [facebookresearch/sapiens#99]
Hi, thank you for your great work!

I would like to perform a finetuning task for body part segmentation, using two GPUs (GPU IDs 4 and 5) on an A800 for training test. However, I found that during training, only one GPU is actually being used.

In the node.sh script, I noticed the following section:

`NUM_GPUS=$((NUM_GPUS_STRING_LEN/2))`
It seems that this part is causing only one GPU to be used. I modified this line to `NUM_GPUS=$((NUM_GPUS_STRING_LEN))`, but I found that the training could not be executed correctly, and the following error occurred:
```
Traceback (most recent call last):
  File "/root/miniforge3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniforge3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/root/miniforge3/lib/python3.10/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/root/miniforge3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniforge3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-18_17:48:34
  host      : dsw-81101-6cfdfcd794-nd5mk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2533286)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

I would like to know why, when only two GPUs are available, only one GPU is participating in the training (without being in debug mode). Under an 8-GPU configuration (DEVICES=0,1,2,3,4,5,6,7), how many GPUs would participate in training?

Additionally, could you give me a rough estimate of how long it would take to finetune 10,000 samples with default parameters?

I'd appreciate it if you can give me some advice?

**Comment by rawalkhirodkar** [comment]
@ShulingTang only change the DEVICES variable to control the number of gpus used. 

It is hard to estimate the exact time on 10k samples with different hardware setup. Around 10 epochs should give good results.

**Comment by ShulingTang** [comment]
Thank you so much for your feedback, and I was wondering if there was an option to speed up my finetune training?

**Comment by rawalkhirodkar** [comment]
@ShulingTang you can change the architecture of the decoder head to gain some speed: https://github.com/facebookresearch/sapiens/blob/3cc7321e97cd630ce9ddcf176fda47edabcd2f47/seg/configs/sapiens_seg/seg_face/sapiens_1b_seg_face-1024x768.py#L64

Other than this, training with automatic mixed precision may also help - this is not supported with the current code.
